# Generated by Django 5.2.16 on 2026-08-05 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0008_curriculumdocument_external_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='العام الدراسي (مثل 2025/2026)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_current', models.BooleanField(default=False, verbose_name='العام الحالي')),
            ],
            options={
                'verbose_name': 'عام دراسي',
                'verbose_name_plural': 'الأعوام الدراسية',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المدرسة')),
                ('school_code', models.CharField(max_length=50, unique=True, verbose_name='الرمز التعريفي للمدرسة (School Code)')),
                ('directorate', models.CharField(blank=True, max_length=255, verbose_name='المديرية التابعة لها')),
                ('translations', models.JSONField(blank=True, default=dict, verbose_name='الترجمات')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'مدرسة',
                'verbose_name_plural': 'المدارس',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=50, verbose_name='رقم المستلم')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('status', models.CharField(choices=[('sent', 'تم الإرسال'), ('failed', 'فشل الإرسال')], default='pending', max_length=20, verbose_name='الحالة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'سجل إشعارات الواتساب',
                'verbose_name_plural': 'سجلات إشعارات الواتساب',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentTeacherTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الاستفسار')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد المعالجة'), ('closed', 'مغلق')], default='open', max_length=20, verbose_name='الحالة')),
                ('messages', models.JSONField(blank=True, default=list, verbose_name='سجل المحادثة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_tickets', to=settings.AUTH_USER_MODEL, verbose_name='ولي الأمر')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tickets', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='academics.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_tickets', to=settings.AUTH_USER_MODEL, verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'تذكرة استفسار ولي أمر',
                'verbose_name_plural': 'تذاكر استفسارات أولياء الأمور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الشعبة (مثل أ، ب، 1)')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schools.academicyear', verbose_name='العام الدراسي')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.grade', verbose_name='الصف الدراسي')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schools.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'شعبة صفية',
                'verbose_name_plural': 'الشعب الصفية',
                'unique_together': {('school', 'grade', 'academic_year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SchoolAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التنبيه / الواجب')),
                ('content', models.TextField(verbose_name='محتوى التنبيه / الواجب')),
                ('is_emergency', models.BooleanField(default=False, verbose_name='حالة طارئة (إرسال واتساب فوري)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='الناشر')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='schools.school', verbose_name='المدرسة')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='schools.section', verbose_name='الشعبة (فارغ للعام)')),
            ],
            options={
                'verbose_name': 'إعلان أو واجب مدرسي',
                'verbose_name_plural': 'الإعلانات والواجبات المدرسية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schools.academicyear', verbose_name='العام الدراسي')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.section', verbose_name='الشعبة الصفية')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسجيل طالب',
                'verbose_name_plural': 'تسجيلات الطلاب',
                'unique_together': {('student', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schools.academicyear', verbose_name='العام الدراسي')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schools.section', verbose_name='الشعبة الصفية')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject', verbose_name='المادة الدراسية')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'إسناد معلم',
                'verbose_name_plural': 'إسنادات المعلمين',
                'unique_together': {('teacher', 'section', 'subject', 'academic_year')},
            },
        ),
    ]
