# Generated by Django 5.2.16 on 2026-08-06 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_complexity', models.CharField(default='simple', max_length=50, verbose_name='تعقيد اللغة')),
                ('tone_preference', models.CharField(default='friendly', max_length=50, verbose_name='نبرة المساعد')),
                ('voice_type', models.CharField(default='default', max_length=50, verbose_name='نوع الصوت')),
                ('context_retrieval', models.BooleanField(default=True, verbose_name='استرجاع السياق المتقدم')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_setting', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعدادات الذكاء الاصطناعي للمستخدم',
                'verbose_name_plural': 'إعدادات الذكاء الاصطناعي للمستخدمين',
            },
        ),
    ]
