# Generated by Django 5.2.16 on 2026-08-06 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_useraisetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['school', 'grade', 'name'], 'verbose_name': 'شعبة صفية', 'verbose_name_plural': 'الشعب الصفية'},
        ),
    ]
