# Generated by Django 5.2.16 on 2026-08-06 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_section_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('translations', models.JSONField(blank=True, default=dict, verbose_name='الترجمات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الحل')], default='open', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب دعم فني',
                'verbose_name_plural': 'طلبات الدعم الفني',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت القراءة')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='schools.schoolannouncement', verbose_name='الإعلان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_receipts', to=settings.AUTH_USER_MODEL, verbose_name='القارئ')),
            ],
            options={
                'verbose_name': 'تأكيد قراءة إعلان',
                'verbose_name_plural': 'تأكيدات قراءة الإعلانات',
                'unique_together': {('announcement', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FamilyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, max_length=50, verbose_name='صلة القرابة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الربط')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_children', to=settings.AUTH_USER_MODEL, verbose_name='ولي الأمر')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_guardians', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'ربط ولي أمر بطالب',
                'verbose_name_plural': 'روابط أولياء الأمور بالطلاب',
                'unique_together': {('parent', 'student')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='بداية الأسبوع')),
                ('summary', models.TextField(verbose_name='التقرير الأسبوعي الملخص')),
                ('assignments_submitted', models.IntegerField(default=0, verbose_name='الواجبات المسلمة')),
                ('attendance_rate', models.FloatField(default=0.0, verbose_name='نسبة الحضور')),
                ('topics_needing_support', models.JSONField(blank=True, default=list, verbose_name='المواضيع التي تحتاج دعم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_weekly_reports', to=settings.AUTH_USER_MODEL, verbose_name='ولي الأمر')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_weekly_reports', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تقرير أسبوعي',
                'verbose_name_plural': 'التقارير الأسبوعية',
                'ordering': ['-week_start'],
                'unique_together': {('student', 'week_start')},
            },
        ),
    ]
