# Generated by Django 5.2.16 on 2026-08-06 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_faq_supportrequest_announcementreadreceipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lesson', 'شرح درس'), ('homework', 'واجب منزلي'), ('submission', 'تسليم واجب')], default='lesson', max_length=20, verbose_name='نوع المرفق')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('file', models.FileField(upload_to='school_attachments/%Y/%m/', verbose_name='الملف / الصورة')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف الأصلي')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الملف')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم الملف (بايت)')),
                ('review_status', models.CharField(choices=[('pending', 'بانتظار المتابعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة المتابعة الإدارية')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attachments', to=settings.AUTH_USER_MODEL, verbose_name='راجعته الإدارة')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='schools.school', verbose_name='المدرسة')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='schools.section', verbose_name='الشعبة')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='الرافع')),
            ],
            options={
                'verbose_name': 'مرفق درس / واجب',
                'verbose_name_plural': 'مرفقات الدروس والواجبات',
                'ordering': ['-created_at'],
            },
        ),
    ]
