# Generated by Django 5.2.16 on 2026-08-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='education_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='نوع التعليم'),
        ),
        migrations.AddField(
            model_name='school',
            name='gender',
            field=models.CharField(blank=True, max_length=50, verbose_name='جنس المؤسسة'),
        ),
        migrations.AddField(
            model_name='school',
            name='governorate',
            field=models.CharField(blank=True, max_length=100, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='الإقليم'),
        ),
    ]
