# Generated by Django 5.2.16 on 2026-08-09 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_curriculumdocument_external_url_and_more'),
        ('schools', '0008_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحصة (مثل الحصة الأولى)')),
                ('period_number', models.IntegerField(default=1, verbose_name='رقم الحصة')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('is_break', models.BooleanField(default=False, verbose_name='استراحة / فسحة')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='schools.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'حصة زمنية',
                'verbose_name_plural': 'الحصص الزمنية',
                'ordering': ['school', 'period_number'],
                'unique_together': {('school', 'period_number')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم القاعة / المختبر')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='رمز القاعة')),
                ('capacity', models.IntegerField(default=30, verbose_name='السعة')),
                ('room_type', models.CharField(choices=[('classroom', 'صف دراسي'), ('lab', 'مختبر علمي'), ('computer_lab', 'مختبر حاسوب'), ('hall', 'قاعة محاضرات / نشاط')], default='classroom', max_length=50, verbose_name='نوع القاعة')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='schools.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'قاعة / مختبر',
                'verbose_name_plural': 'القاعات والمختبرات',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'الأحد'), (1, 'الإثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس')], verbose_name='اليوم')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='schools.academicyear', verbose_name='العام الدراسي')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schools.period', verbose_name='الحصة الزمنية')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='schools.room', verbose_name='القاعة / المختبر')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='schools.school', verbose_name='المدرسة')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='schools.section', verbose_name='الشعبة الصفية')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.subject', verbose_name='المادة الدراسية')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to=settings.AUTH_USER_MODEL, verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'خانة جدول دراسي',
                'verbose_name_plural': 'خانات الجداول الدراسية',
                'ordering': ['section', 'day_of_week', 'period__period_number'],
                'unique_together': {('section', 'day_of_week', 'period')},
            },
        ),
    ]
