# Generated by Django 5.2.16 on 2026-08-10 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_curriculumdocument_external_url_and_more'),
        ('schools', '0009_period_room_timetableslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_count', models.PositiveIntegerField(default=1, verbose_name='عدد الشعب لكل صف')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_offers', to='academics.grade', verbose_name='الصف الدراسي')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_grades', to='schools.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'صف مدرسي معروض',
                'verbose_name_plural': 'الصفوف المعروضة في المدرسة',
                'ordering': ['grade__level'],
                'unique_together': {('school', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='SchoolTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_link', to='schools.school', verbose_name='المدرسة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_links', to=settings.AUTH_USER_MODEL, verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'معلم في مدرسة',
                'verbose_name_plural': 'المعلمون في المدارس',
                'unique_together': {('school', 'teacher')},
            },
        ),
    ]
