# Generated by Django 5.2.16 on 2026-08-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_schoolgrade_schoolteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='capacity',
            field=models.PositiveIntegerField(default=30, verbose_name='السعة الاستيعابية'),
        ),
    ]
