# Generated by Django 5.2.16 on 2026-08-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_curriculumdocument_external_url_and_more'),
        ('schools', '0011_section_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolteacher',
            name='max_weekly_periods',
            field=models.PositiveIntegerField(default=24, verbose_name='النصاب (عدد الحصص الأسبوعية)'),
        ),
        migrations.CreateModel(
            name='SchoolSubjectPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_periods', models.PositiveIntegerField(default=1, verbose_name='عدد الحصص الأسبوعية')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_subject_periods', to='academics.grade', verbose_name='الصف الدراسي')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_periods', to='schools.school', verbose_name='المدرسة')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_subject_periods', to='academics.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'عدد حصص مادة في صف',
                'verbose_name_plural': 'عدد حصص المواد في الصفوف',
                'ordering': ['grade__level', 'id'],
                'unique_together': {('school', 'grade', 'subject')},
            },
        ),
    ]
