# Generated by Django 5.2.16 on 2026-08-12 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_schoolteacher_max_weekly_periods_schoolsubjectperiod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='period',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='period',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الأرشفة'),
        ),
        migrations.AddField(
            model_name='period',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_periods', to=settings.AUTH_USER_MODEL, verbose_name='أرشفها'),
        ),
        migrations.AddField(
            model_name='period',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_periods', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها'),
        ),
        migrations.AddField(
            model_name='period',
            name='generation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الجيل (إصدار الجدول)'),
        ),
        migrations.AddField(
            model_name='period',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعّلة'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'period_number'), name='unique_active_period_per_school'),
        ),
    ]
