# Generated by Django 5.2.16 on 2026-08-14 17:13

import apps.schools.models
from django.db import migrations, models


def remap_day_of_week_to_iso(apps, schema_editor):
    """Legacy TimetableSlot used 0=Sunday..4=Thursday. ISO uses 1=Monday..7=Sunday."""
    TimetableSlot = apps.get_model('schools', 'TimetableSlot')
    mapping = {0: 7, 1: 1, 2: 2, 3: 3, 4: 4}
    for old, new in mapping.items():
        TimetableSlot.objects.filter(day_of_week=old).update(day_of_week=new)


def remap_day_of_week_to_legacy(apps, schema_editor):
    """Reverse mapping (for migration rollback)."""
    TimetableSlot = apps.get_model('schools', 'TimetableSlot')
    mapping = {7: 0, 1: 1, 2: 2, 3: 3, 4: 4}
    for old, new in mapping.items():
        TimetableSlot.objects.filter(day_of_week=old).update(day_of_week=new)


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_section_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='week_start',
            field=models.IntegerField(choices=[(1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس'), (5, 'الجمعة'), (6, 'السبت'), (7, 'الأحد')], default=7, help_text='أول أيام الأسبوع الدراسي (ISO: 1=الاثنين ... 7=الأحد)', verbose_name='بداية الأسبوع'),
        ),
        migrations.AddField(
            model_name='school',
            name='working_days',
            field=models.JSONField(default=apps.schools.models.default_working_days, help_text='أيام الدوام الدراسي كقائمة أرقام ISO (1=الاثنين ... 7=الأحد)', verbose_name='أيام الدوام'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس'), (5, 'الجمعة'), (6, 'السبت'), (7, 'الأحد')], verbose_name='اليوم'),
        ),
        migrations.RunPython(remap_day_of_week_to_iso, remap_day_of_week_to_legacy),
    ]
