# Generated by Django 5.2.16 on 2026-08-15 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_school_week_start_school_working_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الرسوم')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='schools.schoolgrade', verbose_name='الصف الدراسي')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='schools.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'رسوم مدرسية',
                'verbose_name_plural': 'الرسوم المدرسية',
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المستحق')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('status', models.CharField(choices=[('pending', 'غير مسدد'), ('partial', 'مسدد جزئياً'), ('paid', 'مسدد بالكامل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schools.schoolfee', verbose_name='الرسوم')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'ذمة مالية للطالب',
                'verbose_name_plural': 'الذمم المالية للطلاب',
            },
        ),
    ]
