# Generated by Django 5.2.16 on 2026-08-15 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_schoolfee_studentfeeassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=50, verbose_name='رقم الحافلة')),
                ('driver_name', models.CharField(max_length=255, verbose_name='اسم السائق')),
                ('driver_phone', models.CharField(blank=True, max_length=50, verbose_name='هاتف السائق')),
                ('capacity', models.IntegerField(default=30, verbose_name='السعة الاستيعابية')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='schools.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'حافلة مدرسية',
                'verbose_name_plural': 'الحافلات المدرسية',
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=255, verbose_name='اسم الخط')),
                ('morning_time', models.TimeField(blank=True, null=True, verbose_name='وقت التحرك الصباحي')),
                ('evening_time', models.TimeField(blank=True, null=True, verbose_name='وقت العودة المسائي')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='schools.schoolbus', verbose_name='الحافلة')),
            ],
            options={
                'verbose_name': 'خط سير حافلة',
                'verbose_name_plural': 'خطوط سير الحافلات',
            },
        ),
        migrations.CreateModel(
            name='StudentBusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_point', models.CharField(max_length=255, verbose_name='نقطة التجمع / الانتظار')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.busroute', verbose_name='خط السير')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_assignments', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تخصيص حافلة لطالب',
                'verbose_name_plural': 'تخصيص الحافلات للطلاب',
            },
        ),
    ]
