# Generated by Django 5.2.17 on 2026-08-16 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_schoolbus_busroute_studentbusassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الكتاب')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='المؤلف')),
                ('isbn', models.CharField(blank=True, max_length=50, verbose_name='الرقم التسلسلي ISBN')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='التصنيف')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='إجمالي النسخ')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='النسخ المتاحة')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='schools.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'كتاب مدرسي',
                'verbose_name_plural': 'كتب المكتبة المدرسية',
            },
        ),
        migrations.CreateModel(
            name='LibraryLending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الاستعارة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإرجاع الفعلي')),
                ('status', models.CharField(choices=[('borrowed', 'مستعار'), ('returned', 'تم الإرجاع'), ('overdue', 'متأخر')], default='borrowed', max_length=20, verbose_name='الحالة')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendings', to='schools.book', verbose_name='الكتاب')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_lendings', to=settings.AUTH_USER_MODEL, verbose_name='الطالب المستعير')),
            ],
            options={
                'verbose_name': 'عملية إعارة كتاب',
                'verbose_name_plural': 'عمليات إعارة الكتب',
            },
        ),
    ]
