# Generated by Django 5.2.16 on 2026-08-17 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_book_librarylending'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarylending',
            name='student',
        ),
        migrations.AddField(
            model_name='librarylending',
            name='borrower',
            field=models.ForeignKey(blank=True, help_text='الحساب المرتبط بالمستعير إن وُجد (طالب/معلم/ولي أمر).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_lendings', to=settings.AUTH_USER_MODEL, verbose_name='المستعير (حساب مرتبط)'),
        ),
        migrations.AddField(
            model_name='librarylending',
            name='borrower_name',
            field=models.CharField(blank=True, help_text='اسم المستعير الكامل لمتابعة العهدة والاستعارة.', max_length=255, verbose_name='اسم المستعير (للمتابعة)'),
        ),
        migrations.AddField(
            model_name='librarylending',
            name='borrower_role',
            field=models.CharField(choices=[('student', 'طالب'), ('teacher', 'معلم'), ('parent', 'ولي أمر'), ('staff', 'موظف'), ('other', 'أخرى')], default='student', max_length=20, verbose_name='نوع المستعير'),
        ),
    ]
