# Generated by Django 5.2.16 on 2026-08-17 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_curriculum_country_alter_curriculum_year_and_more'),
        ('schools', '0019_remove_librarylending_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الواجب')),
                ('description', models.TextField(blank=True, verbose_name='وصف الواجب')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='موعد التسليم')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='الدرجة النهائية')),
                ('attachment', models.FileField(blank=True, upload_to='assignments/%Y/%m/', verbose_name='مرفق الواجب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schools.section', verbose_name='الشعبة')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'واجب منزلي',
                'verbose_name_plural': 'الواجبات المنزلية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم التقييم')),
                ('weight', models.PositiveIntegerField(default=10, help_text='الوزن النسبي لهذا التقييم من إجمالي الدرجات (1-100)', verbose_name='النسبة المئوية للوزن (%)')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='الدرجة النهائية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_categories', to='schools.school', verbose_name='المدرسة')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_categories', to='academics.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'تصنيف درجات',
                'verbose_name_plural': 'تصنيفات الدرجات',
                'ordering': ['subject', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='submissions/%Y/%m/', verbose_name='ملف الحل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الطالب')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='الدرجة')),
                ('feedback', models.TextField(blank=True, verbose_name='تعليق المعلم')),
                ('status', models.CharField(choices=[('submitted', 'تم التسليم'), ('graded', 'تم التقييم'), ('returned', 'مرجع للمراجعة')], default='submitted', max_length=20, verbose_name='الحالة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسليم')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقييم')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='schools.assignment', verbose_name='الواجب')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL, verbose_name='قيّمها')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسليم واجب',
                'verbose_name_plural': 'تسليمات الواجبات',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الدرجة المحصل عليها')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات المعلم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='schools.gradecategory', verbose_name='التصنيف')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_entries', to=settings.AUTH_USER_MODEL, verbose_name='قيّمها')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='schools.section', verbose_name='الشعبة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'درجة طالب',
                'verbose_name_plural': 'درجات الطلاب',
                'ordering': ['section', 'student__email'],
                'unique_together': {('category', 'student')},
            },
        ),
    ]
