# Generated by Django 5.2.16 on 2026-08-17 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_add_gradebook_and_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='room_allocation_mode',
            field=models.CharField(choices=[('fixed', 'قاعة ثابتة لكل شعبة'), ('mobility', 'تنقل الشعب بين القاعات')], default='fixed', help_text='ثابت: كل شعبة لها قاعة مخصصة. تنقل: الشعبة تتنقل حسب المادة والسعة', max_length=20, verbose_name='وضع تخصيص القاعات'),
        ),
        migrations.AddField(
            model_name='schoolsubjectperiod',
            name='preferred_room_type',
            field=models.CharField(blank=True, choices=[('', 'أي قاعة'), ('classroom', 'صف دراسي'), ('lab', 'مختبر علمي'), ('computer_lab', 'مختبر حاسوب'), ('hall', 'قاعة محاضرات / نشاط')], default='', help_text='نوع القاعة المناسب لهذه المادة في هذا الصف. فارغ = أي قاعة', max_length=50, verbose_name='نوع القاعة المفضل'),
        ),
        migrations.AddField(
            model_name='section',
            name='home_room',
            field=models.ForeignKey(blank=True, help_text='القاعة المخصصة للشعبة في وضع القاعات الثابتة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_sections', to='schools.room', verbose_name='القاعة الصفية'),
        ),
    ]
