# Generated by Django 5.2.16 on 2026-08-19 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_add_room_allocation_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('school_accountant', 'Accountant'), ('school_transport_officer', 'Transport Officer'), ('school_librarian', 'Librarian')], max_length=32, verbose_name='الدور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_link', to='schools.school', verbose_name='المدرسة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_staff_links', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': '_staff member',
                'verbose_name_plural': 'School Staff',
                'unique_together': {('school', 'user', 'role')},
            },
        ),
    ]
