# Generated by Django 5.2.16 on 2026-08-19 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_add_schoolstaff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolManagerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_manager_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني للمدير الجديد')),
                ('new_manager_id', models.IntegerField(blank=True, help_text='Set if user already exists', null=True)),
                ('reason', models.TextField(blank=True, default='', verbose_name='سبب النقل')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_manager_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_manager_requests', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_requests', to='schools.school')),
            ],
            options={
                'verbose_name': 'School Manager Request',
                'verbose_name_plural': 'School Manager Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
