# Generated by Django 5.2.16 on 2026-08-19 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_grade_has_tracks_academictrack_curriculum_track'),
        ('schools', '0023_add_schoolmanagerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsubjectperiod',
            name='track',
            field=models.ForeignKey(blank=True, help_text='فارغ = مادة عامة لكل التخصصات، مملو = مادة خاصة بالتخصص', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_periods', to='academics.academictrack', verbose_name='التخصص'),
        ),
        migrations.AddField(
            model_name='section',
            name='track',
            field=models.ForeignKey(blank=True, help_text='فارغ = صف عام بدون تخصص، مملو = شعبة تابعة لتخصص محدد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='academics.academictrack', verbose_name='التخصص'),
        ),
    ]
