# Generated by Django 5.2.16 on 2026-08-20 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_schoolsubjectperiod_track_section_track'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الجهاز')),
                ('device_type', models.CharField(choices=[('gps_tracker', 'جهاز تتبع GPS'), ('rfid_reader', 'قارئ بطاقات RFID'), ('facial_camera', 'كاميرا التعرف على الوجه'), ('mobile_app', 'تطبيق هاتف السائق'), ('bluetooth_rfid', 'قارئ RFID بلوتوث')], max_length=30, verbose_name='نوع الجهاز')),
                ('device_identifier', models.CharField(max_length=255, unique=True, verbose_name='معرف الجهاز (IMEI / MAC / Serial)')),
                ('api_token', models.CharField(blank=True, default='', max_length=512, verbose_name='مفتاح الأمان (API Token)')),
                ('assigned_gate', models.CharField(blank=True, default='', max_length=100, verbose_name='البوابة / المدخل المخصص')),
                ('status', models.CharField(choices=[('online', 'متصل'), ('offline', 'غير متصل'), ('maintenance', 'صيانة')], default='offline', max_length=20, verbose_name='حالة الاتصال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر اتصال')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('assigned_bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='schools.schoolbus', verbose_name='الحافلة المخصصة')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='schools.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'جهاز مدرسي',
                'verbose_name_plural': 'الأجهزة المدرسية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('rfid_tap', 'مسح بطاقة RFID'), ('facial_recognition', 'التعرف على الوجه'), ('door_open', 'فتح الباب'), ('door_close', 'إغلاق الباب'), ('geofence_enter', 'دخول المنطقة الجغرافية'), ('geofence_exit', 'خروج المنطقة الجغرافية')], max_length=30, verbose_name='نوع الحدث')),
                ('direction', models.CharField(blank=True, choices=[('board', 'صعود'), ('exit', 'نزول')], default='', max_length=10, verbose_name='اتجاه الحركة')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='البيانات الخام')),
                ('timestamp', models.DateTimeField(verbose_name='وقت الحدث')),
                ('processed', models.BooleanField(default=False, verbose_name='تمت المعالجة')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الاستلام')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_events', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schools.schooldevice', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'حدث جهاز',
                'verbose_name_plural': 'أحداث الأجهزة',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='schools_dev_device__bf51c4_idx'), models.Index(fields=['student', '-timestamp'], name='schools_dev_student_2bb150_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0, verbose_name='خط العرض')),
                ('longitude', models.FloatField(default=0.0, verbose_name='خط الطول')),
                ('speed', models.FloatField(default=0.0, verbose_name='السرعة (كم/ساعة)')),
                ('heading', models.FloatField(default=0.0, verbose_name='الاتجاه (درجات)')),
                ('timestamp', models.DateTimeField(verbose_name='وقت الإرسال')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الاستلام')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='schools.schoolbus', verbose_name='الحافلة')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_logs', to='schools.schooldevice', verbose_name='الجهاز المرسل')),
            ],
            options={
                'verbose_name': 'سجل موقع حافلة',
                'verbose_name_plural': 'سجلات مواقع الحافلات',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['bus', '-timestamp'], name='schools_bus_bus_id_3b6bc0_idx')],
            },
        ),
    ]
