# Generated by Django 5.2.16 on 2026-08-03 08:39

from django.db import migrations, models


def backfill_provider(apps, schema_editor):
    Order = apps.get_model('marketplace', 'Order')
    Order.objects.filter(payment_session_id__gt='').update(payment_provider='stripe')


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_order_paid_at_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intent_id',
            new_name='payment_transaction_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='stripe_session_id',
            new_name='payment_session_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_session_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Payment Session ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Payment Transaction ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Payment Provider'),
        ),
        migrations.RunPython(backfill_provider, migrations.RunPython.noop),
    ]
