# Generated by Django 5.2.16 on 2026-08-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_order_stripe_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='JOD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.CharField(default='JOD', max_length=3, verbose_name='Currency'),
        ),
    ]
