# Generated by Django 5.2.16 on 2026-08-19 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_payoutrequest_wallet_wallettransaction'),
        ('users', '0017_add_userrole_and_roles_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='provider_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_services', to='users.userrole', verbose_name='Provider Role'),
        ),
    ]
