# Real verified YouTube data — Elzero + Codezilla + freeCodeCamp

HTML_LESSONS = [
                ("6QAELgirvjs", "تعلم HTML في 2021 - درس 01# - مقدمة وماذا تحتاج لتتعلم"),
                ("7LxA9qXUY5k", "تعلم HTML في 2021 - درس 02# - عناصر اللغة والمتصفح"),
                ("QG5aEmS9Fu0", "تعلم HTML في 2021 - درس 03# - إنشاء مشروعك الأول وصفحتك الأولى"),
                ("dVgTBEYCseU", "تعلم HTML في 2021 - درس 04# - عنصر ال Head والعناصر الداخلية"),
                ("3lXuWHtm7PM", "تعلم HTML في 2021 - درس 05# - التعليقات وأمثلة على إستخدامها"),
                ("sBFemL2Mfj4", "تعلم HTML في 2021 - درس 06# - تعرف على نوع الصفحة Doctype وال Modes بأنواعها"),
                ("XxkX8wnRq3s", "تعلم HTML في 2021 - درس 07# - عناصر العناوين Headings وأمثلة على الإستخدام"),
                ("S58smWj5Yn0", "تعلم HTML في 2021 - درس 08# - بنية ال Code وبعض التجارب المهمة"),
                ("Fpibp-291xQ", "تعلم HTML في 2021 - درس 09# - عنصر الفقرة النصية Paragraph"),
                ("nCpNsMgyzh4", "تعلم HTML في 2021 - درس 10# - سمات العناصر Attributes"),
                ("zhwqvfoi50Q", "تعلم HTML في 2021 - درس 11# - تنسيق العناصر Formatting Elements"),
                ("7TQhxAOjd1w", "تعلم HTML في 2021 - درس 12# - الرابط Link عنصر ال Anchor"),
                ("FmIUk3bWGmU", "تعلم HTML في 2021 - درس 13# - الصور وكيفية التعامل مع المسارات"),
                ("8Z7zR-UGjcQ", "تعلم HTML في 2021 - درس 14# - القوائم بأنواعها UL, OL, DL"),
                ("SUW49Jjxvac", "تعلم HTML في 2021 - درس 15# - الجدول Table"),
                ("T2myRpY2iN4", "تعلم HTML في 2021 - درس 16# - عناصر ال Span والخط الافقى HR"),
                ("IGeh2mlM9Rg", "تعلم HTML في 2021 - درس 17# - عنصر ال Div وكيفية إستخدامه"),
                ("B8raKziIYyY", "تعلم HTML في 2021 - درس 18# - الكيانات HTML Entities"),
]

CSS_LESSONS = [
                ("X1ulCwyhCVM", "Learn CSS In Arabic 2021 - #01 - Introduction And What I Need To Learn"),
                ("89VLfs-wpEY", "Learn CSS In Arabic 2021 - #02 - Your First Project And Syntax"),
                ("66sjwQ-hB64", "Learn CSS In Arabic 2021 - #03 - Element Styling"),
                ("xkNpIsbxMuo", "Learn CSS In Arabic 2021 - #04 - Name Conventions And Rules"),
                ("-srybsn3YDM", "Learn CSS In Arabic 2021 - #05 - Background - Color, Image, Repeat"),
                ("8sooTBY5C4w", "Learn CSS In Arabic 2021 - #06 - Background - Attachment, Position, Size"),
                ("-wdlA-wFv9A", "Learn CSS In Arabic 2021 - #07 - Padding"),
                ("LEJkJ0AiKDw", "Learn CSS In Arabic 2021 - #08 - Margin"),
                ("XE7d1OoljyI", "Learn CSS In Arabic 2021 - #09 - Border"),
                ("NyOaxP-Adac", "Learn CSS In Arabic 2021 - #10 - Outline"),
                ("-qbGxua98To", "Learn CSS In Arabic 2021 - #11 - Display - Block, Inline Block, Inline"),
                ("g2URo6kLtgg", "Learn CSS In Arabic 2021 - #12 - Element Visibility And Use Cases"),
                ("NTccbXHW7AM", "Learn CSS In Arabic 2021 - #13 - Grouping Multiple Selectors"),
                ("wo_S_Mfl3yg", "Learn CSS In Arabic 2021 - #14 - Nesting"),
                ("GIWYpmiv1Hc", "Learn CSS In Arabic 2021 - #15 - Dimensions - Width And Height"),
                ("FQLRSbVdk28", "Learn CSS In Arabic 2021 - #16 - Overflow - Overflow-X And Overflow-Y"),
                ("P3xdm7md7AE", "Learn CSS In Arabic 2021 - #17 - Text - Color And Shadow"),
                ("IqCXELTTymo", "Learn CSS In Arabic 2021 - #18 - Text - Alignment"),
]

JS_LESSONS = [
                ("GM6dQBmc-Xg", "Learn JavaScript In Arabic 2021 - #001 - Introduction And What Is JavaScript ?"),
                ("MAauLwSHO6Y", "Learn JavaScript In Arabic 2021 - #002 - How To Study The Course ?"),
                ("5wAtDN_CLgI", "Learn JavaScript In Arabic 2021 - #003 - Setting Up Environment And Tools"),
                ("ig_1bvufUPo", "Learn JavaScript In Arabic 2021 - #004 - Work With Chrome Developer Tools"),
                ("XQCG-zf71Mk", "Learn JavaScript In Arabic 2021 - #005 - Where To Put The Code"),
                ("x6kJMXxqmNo", "Learn JavaScript In Arabic 2021 - #006 - Comments And Bad Practices"),
                ("FYRypqj4Epw", "Learn JavaScript In Arabic 2021 - #007 - Output To Screen"),
                ("g0SBnmqOvgQ", "Learn JavaScript In Arabic 2021 - #008 - Console Methods And Styling And WebAPI"),
                ("6RLo08fmGXg", "Learn JavaScript In Arabic 2021 - #009 - What Is ECMAScript ?"),
                ("WaMYDuohE1A", "Learn JavaScript In Arabic 2021 - #010 - Data Types And Typeof Operator"),
                ("NgLgguhL2to", "Learn JavaScript In Arabic 2021 - #011 - Variables Introduction"),
                ("8ADaKFTeB3M", "Learn JavaScript In Arabic 2021 - #012 - Identifiers Name Conventions And Rules"),
                ("gyWwPypW4OU", "Learn JavaScript In Arabic 2021 - #013 - Var, Let, Const Compare"),
                ("TzWla9f9VCY", "Learn JavaScript In Arabic 2021 - #014 - String Syntax And Character Escape Sequences"),
                ("ikK5I2gcrag", "Learn JavaScript In Arabic 2021 - #015 - Concatenation"),
                ("8KjqKNlvVXk", "Learn JavaScript In Arabic 2021 - #016 - Template Literals Template Strings"),
                ("rzmKwzHaETI", "Learn JavaScript In Arabic 2021 - #017 - Variable And Concatenation Challenge"),
                ("jhy86kqiSsk", "Learn JavaScript In Arabic 2021 - #018 - Arithmetic Operators"),
]

PY_LESSONS = [
                ("h3VCQjyaLws", "شرح بايثون - تعلم لغة بايثون و اهمية تعلم البرمجة بلغة بايثون؟"),
                ("t-bCLbmgesI", "[ مقدمة كورس تعلم بايثون و اجابة الاسئلة الشائعة - [ تعلم بايثون بالعربي"),
                ("WTRKeSoynKI", "[#00 تثبيت و تنصيب بايثون - [ تعلم بايثون بالعربي"),
                ("SMyzYOPGeD8", "{Install PyCharm} - [#01 تنصيب بايشارم - [ تعلم بايثون بالعربي"),
                ("oMMW_Cx0qW8", "[#02 كتابة اول سطر كود في بايثون - [ تعلم بايثون بالعربي"),
                ("Vl1mHJMrEnk", "[#03 بناء اول برنامج في بايثون - [ تعلم بايثون بالعربي"),
                ("gQxch0k9B0E", "{Python Variables} - [#04 المتغيرات في بايثون - [ تعلم بايثون بالعربي"),
                ("5O_m0IGwQLw", "{Python Strings} - [#05 السلاسل في بايثون - [ تعلم بايثون بالعربي"),
                ("HjfiVp0L3LI", "{Python Numbers} - [#06 الارقام في بايثون - [ تعلم بايثون بالعربي"),
                ("bWE45B_O9Lk", "{Python Inputs} - [#07 المدخلات في بايثون - [ تعلم بايثون بالعربي"),
                ("hYC0ObXfGjs", "{Build Calculator in Python} - [#08 بناء اله حاسبه في بايثون - [ تعلم بايثون بالعربي"),
                ("N57Xvo8ilMw", "{Build MadLibs in Python} - [#09 بناء تطبيق في بايثون - [ تعلم بايثون بالعربي"),
                ("EgwCjNCx_v4", "{Python Lists} - [#10 القوائم في بايثون - [ تعلم بايثون بالعربي"),
                ("SGp9syExKxk", "{Python Lists 2} - [#11 القوائم في بايثون ٢ - [ تعلم بايثون بالعربي"),
                ("PNMSop-0kwM", "{Python Tuples} - [#12 القوائم الثابتة في بايثون - [ تعلم بايثون بالعربي"),
                ("b4AEoHvCD_A", "{Python Functions} - [#13 الدوال في بايثون - [ تعلم بايثون بالعربي"),
                ("HjiAlW4fbRw", "{Python Functions 2} - [#14 الدوال في بايثون ٢ - [ تعلم بايثون بالعربي"),
                ("IT1C46MDoxo", "{Python Conditionals} - [#15 الادوات الشرطية في بايثون - [ تعلم بايثون بالعربي"),
]
