line-length = 100
target-version = "py311"
extend-exclude = ["*/migrations/*", "*/venv/*"]

[lint]
select = ["E", "F", "W", "I", "UP", "B", "C4", "SIM"]
ignore = ["E501"]

[lint.per-file-ignores]
"config/settings/*.py" = ["E402", "F403", "F405"]
"seed_*.py" = ["E402"]
