"""
Seed script — creates the three main pages with their blocks.
Run: python seed_pages.py
"""
import os
import sys

import django

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings.base')
django.setup()

from apps.pages.models import Page, PageBlock
from apps.core.cache import invalidate_site_cache

# ════════════════════════════════════════════════════════════════
# Page definitions
# ════════════════════════════════════════════════════════════════

PAGES = [ { 'is_homepage': True,
    'nav_icon': '🏠',
    'nav_order': 0,
    'show_in_nav': True,
    'slug': 'homepage',
    'template': 'landing',
    'translations': { 'ar': { 'description': 'منصة الخدمات الرقمية والتعليم',
                              'meta_title': 'آفاق تكنولوجي — منصة الخدمات الرقمية والتعليم',
                              'title': 'منصة آفاق تكنولوجي'},
                      'en': { 'description': 'Digital services and education platform',
                              'meta_title': 'Afaq Tech — Digital Services & Education Platform',
                              'title': 'Afaq Tech Platform'}}},
  { 'is_homepage': False,
    'nav_icon': '🏫',
    'nav_order': 1,
    'show_in_nav': True,
    'slug': 'school',
    'template': 'landing',
    'translations': { 'ar': { 'description': 'منصة آفاق مدرستي لإدارة المدارس وجداول الحصص ومتابعة الطلاب',
                              'meta_title': 'آفاق مدرستي — إدارة المدارس والبرامج الذكية',
                              'title': 'آفاق مدرستي'},
                      'en': { 'description': 'Afaq Madrasti: school management and daily follow-up',
                              'meta_title': 'Afaq Madrasti — School Management & Timetables',
                              'title': 'Afaq Madrasti'}}},
  { 'is_homepage': False,
    'nav_icon': '🎓',
    'nav_order': 1,
    'show_in_nav': True,
    'slug': 'academy',
    'template': 'landing',
    'translations': { 'ar': { 'description': 'منصة التعليم غير الرسمي بالذكاء الاصطناعي',
                              'meta_title': 'أكاديمية آفاق — تعلم بالذكاء الاصطناعي',
                              'title': 'أكاديمية آفاق'},
                      'en': { 'description': 'Non-formal education platform with AI-powered learning',
                              'meta_title': 'Afaq Academy — Learn with AI',
                              'title': 'Afaq Academy'}}},
  { 'is_homepage': False,
    'nav_icon': '📚',
    'nav_order': 2,
    'show_in_nav': True,
    'slug': 'curriculum',
    'template': 'landing',
    'translations': { 'ar': { 'description': 'دعم المناهج الدراسية المدرسية والجامعية',
                              'meta_title': 'المنهاج الدراسي — دعم المنهج المدرسي والجامعي',
                              'title': 'المنهاج الدراسي'},
                      'en': { 'description': 'School and university curriculum support',
                              'meta_title': 'Academic Curriculum — School & University Support',
                              'title': 'Academic Curriculum'}}},
  { 'is_homepage': False,
    'nav_icon': 'ℹ️',
    'nav_order': 3,
    'show_in_nav': True,
    'slug': 'about',
    'template': 'landing',
    'translations': { 'ar': { 'description': 'تعرّف على رؤيتنا ورسالتنا',
                              'meta_title': 'من نحن — منصة آفاق تكنولوجي',
                              'title': 'عن آفاق تكنولوجي'},
                      'en': { 'description': 'Learn about our mission and vision',
                              'meta_title': 'About Us — Afaq Tech Platform',
                              'title': 'About Afaq Tech'}}},
  { 'is_homepage': False,
    'nav_icon': '📞',
    'nav_order': 4,
    'show_in_nav': True,
    'slug': 'contact',
    'template': 'landing',
    'translations': { 'ar': { 'description': 'تواصل مع فريقنا لنفتح معاً آفاق جديدة لأعمالك',
                              'meta_title': 'تواصل معنا — آفاق تكنولوجي',
                              'title': 'تواصل معنا'},
                      'en': { 'description': 'Get in touch with our team',
                              'meta_title': 'Contact Us — Afaq Tech',
                              'title': 'Contact Us'}}},
  { 'is_homepage': False,
    'nav_order': 10,
    'show_in_nav': False,
    'slug': 'privacy',
    'template': 'landing',
    'translations': { 'ar': { 'description': 'كيف نحمي بياناتك ونحافظ على خصوصيتك',
                              'meta_title': 'سياسة الخصوصية — آفاق تكنولوجي',
                              'title': 'سياسة الخصوصية'},
                      'en': { 'description': 'How we protect your data',
                              'meta_title': 'Privacy Policy — Afaq Tech',
                              'title': 'Privacy Policy'}}},
  { 'is_homepage': False,
    'nav_order': 11,
    'show_in_nav': False,
    'slug': 'terms',
    'template': 'landing',
    'translations': { 'ar': { 'description': 'الشروط والأحكام لاستخدام منصتنا',
                              'meta_title': 'شروط الخدمة — آفاق تكنولوجي',
                              'title': 'شروط الخدمة'},
                      'en': { 'description': 'Terms and conditions for using our platform',
                              'meta_title': 'Terms of Service — Afaq Tech',
                              'title': 'Terms of Service'}}},
  { 'is_homepage': False,
    'nav_order': 20,
    'show_in_nav': False,
    'slug': 'services/web-design',
    'template': 'landing',
    'translations': { 'ar': { 'description': 'خدمات تصميم مواقع احترافية تفتح آفاقاً جديدة لعلامتك التجارية',
                              'meta_title': 'تصميم المواقع — آفاق تكنولوجي',
                              'title': 'تصميم المواقع'},
                      'en': { 'description': 'Professional website design services',
                              'meta_title': 'Web Design — Afaq Tech',
                              'title': 'Web Design'}}},
  { 'is_homepage': False,
    'nav_order': 21,
    'show_in_nav': False,
    'slug': 'services/social-media',
    'template': 'landing',
    'translations': { 'ar': { 'description': 'إدارة احترافية لوسائل التواصل توسّع آفاق حضورك الرقمي',
                              'meta_title': 'إدارة التواصل الاجتماعي — آفاق تكنولوجي',
                              'title': 'إدارة التواصل الاجتماعي'},
                      'en': { 'description': 'Professional social media management',
                              'meta_title': 'Social Media Management — Afaq Tech',
                              'title': 'Social Media Management'}}},
  { 'is_homepage': False,
    'nav_order': 22,
    'show_in_nav': False,
    'slug': 'services/landing-pages',
    'template': 'landing',
    'translations': { 'ar': { 'description': 'صفحات هبوط تفتح آفاق التحويل العالية',
                              'meta_title': 'صفحات الهبوط — آفاق تكنولوجي',
                              'title': 'صفحات الهبوط'},
                      'en': { 'description': 'High-converting landing pages',
                              'meta_title': 'Landing Pages — Afaq Tech',
                              'title': 'Landing Pages'}}},
  { 'is_homepage': False,
    'nav_order': 23,
    'show_in_nav': False,
    'slug': 'services/forms',
    'template': 'landing',
    'translations': { 'ar': { 'description': 'نماذج ذكية تفتح آفاق جمع البيانات بكفاءة',
                              'meta_title': 'النماذج الإلكترونية — آفاق تكنولوجي',
                              'title': 'النماذج الإلكترونية'},
                      'en': { 'description': 'Smart data collection forms',
                              'meta_title': 'Electronic Forms — Afaq Tech',
                              'title': 'Electronic Forms'}}},
  { 'is_homepage': False,
    'nav_order': 24,
    'show_in_nav': False,
    'slug': 'services/ebooks',
    'template': 'landing',
    'translations': { 'ar': { 'description': 'إنتاج كتب رقمية يفتح لك آفاقاً جديدة في عالم المحتوى والريادة',
                              'meta_title': 'الكتب الإلكترونية — آفاق تكنولوجي',
                              'title': 'الكتب الإلكترونية'},
                      'en': { 'description': 'Professional digital book production',
                              'meta_title': 'E-Books — Afaq Tech',
                              'title': 'E-Books'}}},
  { 'is_homepage': False,
    'nav_order': 25,
    'show_in_nav': False,
    'slug': 'services/ad-campaigns',
    'template': 'landing',
    'translations': { 'ar': { 'description': 'حملات إعلانية تفتح لك آفاقاً واسعة من الزوار والعملاء',
                              'meta_title': 'الحملات الإعلانية — آفاق تكنولوجي',
                              'title': 'الحملات الإعلانية'},
                      'en': { 'description': 'Effective advertising campaigns',
                              'meta_title': 'Ad Campaigns — Afaq Tech',
                              'title': 'Ad Campaigns'}}},
  { 'is_homepage': False,
    'nav_order': 26,
    'show_in_nav': False,
    'slug': 'services/brand-identity',
    'template': 'landing',
    'translations': { 'ar': { 'description': 'نبتكر هوية تفتح لك آفاق التميّز مع استشارات تضعك على خارطة النجاح',
                              'meta_title': 'الهوية البصرية — آفاق تكنولوجي',
                              'title': 'الهوية البصرية والاستشارات'},
                      'en': { 'description': 'Complete brand identity and consulting',
                              'meta_title': 'Brand Identity — Afaq Tech',
                              'title': 'Brand Identity & Consulting'}}},
  { 'is_homepage': False,
    'nav_order': 25,
    'show_in_nav': False,
    'slug': 'services/education-platform',
    'template': 'landing',
    'translations': { 'ar': { 'description': 'منصة تعليمية بالذكاء الاصطناعي للمعلمين والطلاب',
                              'meta_title': 'المنصة التعليمية — آفاق تكنولوجي',
                              'title': 'المنصة التعليمية'},
                      'en': { 'description': 'AI-powered educational platform for teachers and students',
                              'meta_title': 'Educational Platform — Afaq Tech',
                              'title': 'Educational Platform'}}},
  { 'is_homepage': False,
    'layout_config': {'background': 'var(--color-background)', 'max_width': '100%', 'padding': '0'},
    'nav_icon': '🤖',
    'nav_order': 5,
    'show_in_nav': True,
    'slug': 'ai-chat',
    'template': 'default',
    'translations': { 'ar': { 'description': 'مساعد ذكي يعمل بالذكاء الاصطناعي للإجابة على أسئلتك ومساعدتك في مهامك',
                              'meta_title': 'المساعد الذكي — آفاق تكنولوجي',
                              'title': 'المساعد الذكي'},
                      'en': { 'description': 'An intelligent AI assistant to answer your questions and help with your '
                                             'tasks',
                              'meta_title': 'AI Assistant — Afaq Tech',
                              'title': 'AI Assistant'}}}]

if __name__ == '__main__':
    for page_data in PAGES:
        blocks_data = page_data.pop('blocks', [])
        page, was_created = Page.objects.update_or_create(
            slug=page_data["slug"],
            defaults=page_data,
        )
        print(f"{'Created' if was_created else 'Updated'}: {page.title}")
        for i, b_data in enumerate(blocks_data):
            block, b_created = PageBlock.objects.update_or_create(
                page=page,
                block_type=b_data['block_type'],
                order=b_data.get('order', i),
                defaults={'content': b_data.get('content', {}), 'styles': b_data.get('styles', {}), 'layout': b_data.get('layout', {}), 'animation': b_data.get('animation', {}), 'is_active': b_data.get('is_active', True)}
            )
            print(f"    Block: {block.get_block_type_display()} (order={block.order})")
    invalidate_site_cache()
    print("Done! Pages: {len(PAGES)}, Blocks: {sum(len(p.get('blocks', [])) for p in PAGES)}")
    print("Site cache invalidated and warmed up.")
