# Generated by Django 5.2.16 on 2026-08-07 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True, verbose_name='Endpoint')),
                ('p256dh', models.CharField(max_length=256, verbose_name='p256dh')),
                ('auth', models.CharField(max_length=128, verbose_name='Auth')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'اشتراك إشعارات متصفح',
                'verbose_name_plural': 'اشتراكات إشعارات المتصفح',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('review', 'Review'), ('announcement', 'Announcement'), ('ticket', 'Ticket'), ('badge', 'Badge'), ('system', 'System')], default='system', max_length=20, verbose_name='Type')),
                ('icon', models.CharField(blank=True, default='', max_length=16, verbose_name='Icon')),
                ('title', models.JSONField(default=dict, verbose_name='العنوان (متعدد اللغات)')),
                ('body', models.JSONField(default=dict, verbose_name='المحتوى (متعدد اللغات)')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='الرابط')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
