# Generated by Django 5.2.16 on 2026-07-27 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name (AR)')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Description (EN)')),
                ('description_ar', models.TextField(blank=True, default='', verbose_name='Description (AR)')),
                ('icon', models.CharField(default='📁', max_length=10, verbose_name='Icon')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Title (AR)')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt_en', models.TextField(blank=True, default='', max_length=500, verbose_name='Excerpt (EN)')),
                ('excerpt_ar', models.TextField(blank=True, default='', max_length=500, verbose_name='Excerpt (AR)')),
                ('content_en', models.TextField(blank=True, default='', verbose_name='Content (EN)')),
                ('content_ar', models.TextField(blank=True, default='', verbose_name='Content (AR)')),
                ('featured_image', models.URLField(blank=True, default='', verbose_name='Featured Image URL')),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated tags', max_length=500, verbose_name='Tags')),
                ('related_service', models.CharField(blank=True, default='', help_text='e.g. /services/web-design', max_length=200, verbose_name='Related Service URL')),
                ('author_name_en', models.CharField(default='Afaq Tech Team', max_length=100, verbose_name='Author Name (EN)')),
                ('author_name_ar', models.CharField(default='فريق آفاق تكنولوجي', max_length=100, verbose_name='Author Name (AR)')),
                ('author_avatar', models.URLField(blank=True, default='', verbose_name='Author Avatar URL')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('read_time', models.IntegerField(default=5, verbose_name='Read Time (minutes)')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
