# Generated by Django 5.2.16 on 2026-07-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_populate_translations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['order', 'slug'], 'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_name_ar',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_name_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_ar',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt_ar',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_en',
        ),
    ]
