# Generated by Django 5.2.16 on 2026-07-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='translations',
            field=models.JSONField(blank=True, default=dict, verbose_name='الترجمات'),
        ),
    ]
