# Generated by Django 5.2.16 on 2026-07-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_populate_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name_en',
        ),
    ]
