# Generated by Django 5.2.16 on 2026-07-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_old_en_ar_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'مجاني'), ('basic', 'أساسي'), ('pro', 'برو'), ('enterprise', 'مؤسسي')], default='free', max_length=20, verbose_name='باقة الاشتراك'),
        ),
    ]
