# Generated by Django 5.2.16 on 2026-07-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.JSONField(blank=True, default=list, verbose_name='الشارات'),
        ),
        migrations.AddField(
            model_name='user',
            name='lessons_created_count',
            field=models.IntegerField(default=0, verbose_name='عدد الخطط المنشأة'),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, verbose_name='النقاط'),
        ),
    ]
