# Generated by Django 5.2.16 on 2026-08-01 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_badges_user_lessons_created_count_user_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='badges',
            field=models.JSONField(blank=True, default=list, verbose_name='Badges'),
        ),
        migrations.AlterField(
            model_name='user',
            name='input_language',
            field=models.CharField(default='ar', max_length=5, verbose_name='Input Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lessons_created_count',
            field=models.IntegerField(default=0, verbose_name='Lessons Created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='output_language',
            field=models.CharField(default='ar', max_length=5, verbose_name='Output Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('creator', 'Content Creator'), ('admin', 'Admin')], default='student', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='Subscription Plan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Asia/Amman', max_length=50, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='translations',
            field=models.JSONField(blank=True, default=dict, verbose_name='Translations'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ui_language',
            field=models.CharField(default='ar', max_length=5, verbose_name='UI Language'),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(default='verify_email', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification',
                'verbose_name_plural': 'Email Verifications',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('successful', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'indexes': [models.Index(fields=['email', 'attempted_at'], name='users_login_email_5815ec_idx')],
            },
        ),
    ]
