# Generated by Django 5.2.16 on 2026-08-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_options_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('school', 'School'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='Subscription Plan'),
        ),
    ]
