# Generated by Django 5.2.16 on 2026-08-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Preferred Currency'),
        ),
    ]
