# Generated by Django 5.2.16 on 2026-08-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_preferred_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='National ID'),
        ),
    ]
