# Generated by Django 5.2.16 on 2026-08-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_expand_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('creator', 'Content Creator'), ('admin', 'System Admin'), ('school_admin', 'School Admin'), ('developer', 'Developer'), ('support', 'Support'), ('content_manager', 'Content Manager'), ('finance', 'Finance')], default='student', max_length=20, verbose_name='Role'),
        ),
    ]
