# Generated by Django 5.2.16 on 2026-08-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_phone_verified_phoneverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('user', 'General User'), ('teacher', 'Teacher'), ('instructor', 'Instructor'), ('parent', 'Parent'), ('creator', 'Content Creator'), ('admin', 'System Admin'), ('school_admin', 'School Admin'), ('developer', 'Developer'), ('support', 'Support'), ('content_manager', 'Content Manager'), ('finance', 'Finance')], default='student', max_length=20, verbose_name='Role'),
        ),
    ]
