# Generated by Django 5.2.16 on 2026-08-19 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_currency'),
        ('users', '0016_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='List of all roles this user has. e.g. ["teacher", "instructor"]', verbose_name='All Roles'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('user', 'General User'), ('teacher', 'Teacher'), ('instructor', 'Instructor'), ('parent', 'Parent'), ('creator', 'Content Creator'), ('admin', 'System Admin'), ('school_admin', 'School Admin'), ('school_accountant', 'School Accountant'), ('school_transport_officer', 'School Transport Officer'), ('school_librarian', 'School Librarian'), ('developer', 'Developer'), ('support', 'Support'), ('content_manager', 'Content Manager'), ('finance', 'Finance')], max_length=32, verbose_name='Role')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('organization', models.ForeignKey(blank=True, help_text='Leave empty for global roles (admin, instructor, provider)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='subscriptions.organization', verbose_name='Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'unique_together': {('user', 'role', 'organization')},
            },
        ),
    ]
