# Generated by Django 5.2.16 on 2026-08-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_add_userrole_and_roles_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('user', 'General User'), ('teacher', 'Teacher'), ('instructor', 'Instructor'), ('parent', 'Parent'), ('creator', 'Content Creator'), ('admin', 'System Admin'), ('school_admin', 'School Admin'), ('school_accountant', 'School Accountant'), ('school_transport_officer', 'School Transport Officer'), ('school_librarian', 'School Librarian'), ('developer', 'Developer'), ('support', 'Support'), ('content_manager', 'Content Manager'), ('finance', 'Finance')], default='user', max_length=32, verbose_name='Role'),
        ),
    ]
