# Generated by Django 5.2.16 on 2026-08-19 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_change_default_role_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('instructor', 'Instructor / Trainer'), ('publisher', 'Publisher'), ('provider', 'Service Provider')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('content_ownership_confirmed', models.BooleanField(default=False)),
                ('platform_rights_granted', models.BooleanField(default=False)),
                ('legal_review_acknowledged', models.BooleanField(default=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_terms', models.TextField(blank=True, default='')),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_role_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Request',
                'verbose_name_plural': 'Role Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
