# Generated by Django 5.2.16 on 2026-07-24 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('plan_data', models.JSONField(verbose_name='بيانات الخطة')),
                ('generated_by', models.CharField(default='ai', max_length=10, verbose_name='مولّد بواسطة')),
                ('ai_model_used', models.CharField(blank=True, max_length=100, verbose_name='نموذج AI المستخدم')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'أرشيف')], default='draft', max_length=15, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='academics.grade')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='academics.subject')),
            ],
            options={
                'verbose_name': 'خطة درس',
                'verbose_name_plural': 'خطط الدروس',
                'ordering': ['-created_at'],
            },
        ),
    ]
