# Generated by Django 5.2.16 on 2026-07-29 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='clones_count',
            field=models.IntegerField(default=0, verbose_name='عدد الاستنساخات'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='downloads_count',
            field=models.IntegerField(default=0, verbose_name='عدد التحميلات'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='مشاركة عامة (Marketplace)'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='عدد الإعجابات'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='original_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='lessonplans.lessonplan', verbose_name='الخطة الأصلية'),
        ),
        migrations.CreateModel(
            name='LessonPlanRefinement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.TextField(verbose_name='طلب التعديل')),
                ('ai_response', models.TextField(verbose_name='رد الذكاء الاصطناعي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعديل')),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refinements', to='lessonplans.lessonplan', verbose_name='خطة الدرس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعديل تفاعلي للخطة',
                'verbose_name_plural': 'تعديلات خطط الدروس التفاعلية',
                'ordering': ['created_at'],
            },
        ),
    ]
