# Generated by Django 5.2.16 on 2026-08-04 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0003_lessonplan_clones_count_lessonplan_downloads_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lesson Plan', 'verbose_name_plural': 'Lesson Plans'},
        ),
        migrations.AlterModelOptions(
            name='lessonplanrefinement',
            options={'ordering': ['created_at'], 'verbose_name': 'Lesson Plan Refinement', 'verbose_name_plural': 'Lesson Plan Refinements'},
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='ai_model_used',
            field=models.CharField(blank=True, max_length=100, verbose_name='AI Model Used'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='clones_count',
            field=models.IntegerField(default=0, verbose_name='Clones Count'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='downloads_count',
            field=models.IntegerField(default=0, verbose_name='Downloads Count'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='generated_by',
            field=models.CharField(default='ai', max_length=10, verbose_name='Generated By'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public (Marketplace)'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Likes Count'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='original_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='lessonplans.lessonplan', verbose_name='Original Plan'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='plan_data',
            field=models.JSONField(verbose_name='Plan Data'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='lessonplanrefinement',
            name='ai_response',
            field=models.TextField(verbose_name='AI Response'),
        ),
        migrations.AlterField(
            model_name='lessonplanrefinement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='lessonplanrefinement',
            name='lesson_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refinements', to='lessonplans.lessonplan', verbose_name='Lesson Plan'),
        ),
        migrations.AlterField(
            model_name='lessonplanrefinement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='lessonplanrefinement',
            name='user_prompt',
            field=models.TextField(verbose_name='Refinement Prompt'),
        ),
    ]
