# Generated by Django 5.2.16 on 2026-07-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('icon', models.CharField(default='🎨', max_length=10, verbose_name='Icon')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('description_ar', models.CharField(blank=True, max_length=255, verbose_name='الوصف بالعربية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('primary', models.CharField(default='#4F46E5', max_length=7, verbose_name='اللون الرئيسي')),
                ('secondary', models.CharField(default='#7C3AED', max_length=7, verbose_name='اللون الثانوي')),
                ('accent', models.CharField(default='#6366F1', max_length=7, verbose_name='اللون المميز')),
                ('success', models.CharField(default='#10B981', max_length=7, verbose_name='لون النجاح')),
                ('error', models.CharField(default='#EF4444', max_length=7, verbose_name='لون الخطأ')),
                ('warning', models.CharField(default='#F59E0B', max_length=7, verbose_name='لون التحذير')),
                ('background', models.CharField(default='#F8FAFC', max_length=7, verbose_name='لون الخلفية')),
                ('surface', models.CharField(default='#FFFFFF', max_length=7, verbose_name='لون السطح')),
                ('surface_alt', models.CharField(default='#F1F5F9', max_length=7, verbose_name='لون السطح البديل')),
                ('text_color', models.CharField(default='#0F172A', max_length=7, verbose_name='لون النص')),
                ('text_secondary', models.CharField(default='#475569', max_length=7, verbose_name='لون النص الثانوي')),
                ('text_muted', models.CharField(default='#94A3B8', max_length=7, verbose_name='لون النص الخافت')),
                ('border_color', models.CharField(default='#E2E8F0', max_length=7, verbose_name='لون الحدود')),
                ('border_light', models.CharField(default='#F1F5F9', max_length=7, verbose_name='لون الحدود الفاتح')),
                ('muted', models.CharField(default='#F1F5F9', max_length=7, verbose_name='اللون الخافت')),
                ('btn_shape', models.CharField(choices=[('rounded', 'مدوّر'), ('pill', 'كبسولة'), ('square', 'مربع')], default='rounded', max_length=10, verbose_name='شكل الأزرار')),
                ('btn_size', models.CharField(default='md', max_length=5, verbose_name='حجم الأزرار')),
                ('btn_shadow', models.CharField(choices=[('none', 'بدون'), ('sm', 'خفيف'), ('md', 'متوسط'), ('lg', 'كبير')], default='md', max_length=5, verbose_name='ظل الأزرار')),
                ('btn_hover', models.CharField(choices=[('none', 'بدون'), ('scale', 'تكبير'), ('shadow', 'ظل'), ('glow', 'توهّج')], default='scale', max_length=10, verbose_name='تأثير Hover')),
                ('card_radius', models.CharField(choices=[('none', 'بدون'), ('sm', 'صغير'), ('md', 'متوسط'), ('lg', 'كبير'), ('full', 'دائري')], default='lg', max_length=10, verbose_name='زوايا البطاقات')),
                ('card_border', models.CharField(default='thin', max_length=10, verbose_name='حدود البطاقات')),
                ('card_shadow', models.CharField(choices=[('none', 'بدون'), ('sm', 'خفيف'), ('md', 'متوسط'), ('lg', 'كبير')], default='md', max_length=5, verbose_name='ظل البطاقات')),
                ('card_glass', models.BooleanField(default=True, verbose_name='تأثير Glass')),
                ('font_heading', models.CharField(default="'IBM Plex Sans Arabic', sans-serif", max_length=200, verbose_name='خط العناوين')),
                ('font_body', models.CharField(default="'Noto Sans Arabic', sans-serif", max_length=200, verbose_name='خط النص')),
                ('font_size', models.CharField(default='16px', max_length=10, verbose_name='حجم الخط')),
                ('line_height', models.CharField(default='1.6', max_length=10, verbose_name='ارتفاع السطر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'ثيم',
                'verbose_name_plural': 'الثيمات',
                'ordering': ['order', 'name'],
            },
        ),
    ]
