# Generated by Django 5.2.16 on 2026-07-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='مفتاح الميزة')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الميزة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'ميزة النظام',
                'verbose_name_plural': 'ميزات النظام (Feature Flags)',
            },
        ),
    ]
