# Generated by Django 5.2.16 on 2026-08-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='رمز اللغة')),
                ('name', models.CharField(max_length=100, verbose_name='اسم اللغة (إنجليزي)')),
                ('native_name', models.CharField(blank=True, max_length=100, verbose_name='اسم اللغة بالعربية')),
                ('flag', models.CharField(blank=True, max_length=20, verbose_name='العلم')),
                ('is_rtl', models.BooleanField(default=False, verbose_name='اتجاه من اليمين لليسار')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('is_default', models.BooleanField(default=False, verbose_name='الافتراضية')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['order', 'code'],
            },
        ),
    ]
