# Generated by Django 5.2.16 on 2026-08-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='المفتاح')),
                ('namespace', models.CharField(blank=True, default='', max_length=100, verbose_name='النطاق')),
                ('translations', models.JSONField(blank=True, default=dict, verbose_name='الترجمات')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'مفتاح ترجمة',
                'verbose_name_plural': 'مفاتيح الترجمة',
                'ordering': ['order', 'key'],
            },
        ),
    ]
