# Generated by Django 5.2.16 on 2026-08-22 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_datadeletionrequest_dataprocessinglog_directorate_and_more'),
        ('schools', '0026_busstop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleclassroomsynclog',
            name='sync_type',
            field=models.CharField(choices=[('import_students', 'Import Students'), ('import_teachers', 'Import Teachers'), ('export_grades', 'Export Grades'), ('sync_assignments', 'Sync Assignments'), ('teacher_send_grades', 'Teacher Send Grades'), ('teacher_sync_assignments', 'Teacher Sync Assignments')], max_length=30),
        ),
        migrations.CreateModel(
            name='GoogleClassroomCourseSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_course_id', models.CharField(max_length=100)),
                ('classroom_course_name', models.CharField(max_length=255)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_syncs', to='schools.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_course_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Google Classroom Course Syncs',
                'unique_together': {('teacher', 'classroom_course_id')},
            },
        ),
    ]
