# Generated by Django 5.2.16 on 2026-07-25 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم (إنجليزي)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم (عربي)')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='الرابط')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='الوصف (إنجليزي)')),
                ('description_ar', models.TextField(blank=True, default='', verbose_name='الوصف (عربي)')),
                ('thumbnail', models.URLField(blank=True, default='', verbose_name='صورة مصغرة')),
                ('category', models.CharField(choices=[('landing', 'صفحة هبوط'), ('business', 'صفحة أعمال'), ('education', 'صفحة تعليمية'), ('portfolio', 'معرض أعمال'), ('custom', 'مخصص')], default='custom', max_length=20, verbose_name='التصنيف')),
                ('default_blocks', models.JSONField(blank=True, default=list, verbose_name='البلوكات الافتراضية')),
                ('default_layout', models.JSONField(blank=True, default=dict, verbose_name='التخطيط الافتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب صفحة',
                'verbose_name_plural': 'قوالب الصفحات',
                'ordering': ['category', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('site_name_en', models.CharField(default='Afaq Tech', max_length=200, verbose_name='اسم الموقع (إنجليزي)')),
                ('site_name_ar', models.CharField(default='آفاق تكنولوجي', max_length=200, verbose_name='اسم الموقع (عربي)')),
                ('site_description_en', models.TextField(blank=True, default='', verbose_name='وصف الموقع (إنجليزي)')),
                ('site_description_ar', models.TextField(blank=True, default='', verbose_name='وصف الموقع (عربي)')),
                ('logo_url', models.URLField(blank=True, default='', verbose_name='شعار الموقع')),
                ('favicon_url', models.URLField(blank=True, default='', verbose_name='Favicon')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='الهاتف')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=50, verbose_name='واتساب')),
                ('facebook_url', models.URLField(blank=True, default='', verbose_name='فيسبوك')),
                ('twitter_url', models.URLField(blank=True, default='', verbose_name='تويتر')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='إنستقرام')),
                ('linkedin_url', models.URLField(blank=True, default='', verbose_name='لينكدإن')),
                ('youtube_url', models.URLField(blank=True, default='', verbose_name='يوتيوب')),
                ('footer_text_en', models.TextField(blank=True, default='', verbose_name='نص التذييل (إنجليزي)')),
                ('footer_text_ar', models.TextField(blank=True, default='', verbose_name='نص التذييل (عربي)')),
                ('copyright_text', models.CharField(blank=True, default='', max_length=200, verbose_name='نصحقوق النشر')),
                ('custom_settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات مخصصة')),
                ('is_active', models.BooleanField(default=True, primary_key=True, serialize=False, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='الرابط')),
                ('title_en', models.CharField(max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('title_ar', models.CharField(max_length=200, verbose_name='العنوان (عربي)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='الوصف (إنجليزي)')),
                ('description_ar', models.TextField(blank=True, default='', verbose_name='الوصف (عربي)')),
                ('template', models.CharField(choices=[('default', 'افتراضي'), ('landing', 'صفحة هبوط'), ('about', 'من نحن'), ('contact', 'تواصل معنا'), ('custom', 'مخصص')], default='default', max_length=20, verbose_name='القالب')),
                ('meta_title_en', models.CharField(blank=True, default='', max_length=200, verbose_name='عنوان SEO (إنجليزي)')),
                ('meta_title_ar', models.CharField(blank=True, default='', max_length=200, verbose_name='عنوان SEO (عربي)')),
                ('meta_description_en', models.TextField(blank=True, default='', verbose_name='وصف SEO (إنجليزي)')),
                ('meta_description_ar', models.TextField(blank=True, default='', verbose_name='وصف SEO (عربي)')),
                ('show_in_nav', models.BooleanField(default=False, verbose_name='إظهار في القائمة')),
                ('nav_order', models.IntegerField(default=0, verbose_name='ترتيب القائمة')),
                ('nav_icon', models.CharField(blank=True, default='', max_length=10, verbose_name='أيقونة القائمة')),
                ('layout_config', models.JSONField(blank=True, default=dict, verbose_name='تخطيط الصفحة')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشورة')),
                ('is_homepage', models.BooleanField(default=False, verbose_name='الصفحة الرئيسية')),
                ('theme_overrides', models.JSONField(blank=True, default=dict, verbose_name='تخصيص الثيم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.page', verbose_name='الصفحة الأب')),
            ],
            options={
                'verbose_name': 'صفحة',
                'verbose_name_plural': 'الصفحات',
                'ordering': ['nav_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(choices=[('header', 'القائمة العلوية'), ('footer', 'تذييل الصفحة'), ('sidebar', 'الشريط الجانبي')], default='header', max_length=20, verbose_name='القائمة')),
                ('title_en', models.CharField(max_length=100, verbose_name='العنوان (إنجليزي)')),
                ('title_ar', models.CharField(max_length=100, verbose_name='العنوان (عربي)')),
                ('url', models.CharField(blank=True, default='', max_length=500, verbose_name='الرابط')),
                ('icon', models.CharField(blank=True, default='', max_length=10, verbose_name='الأيقونة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('open_in_new', models.BooleanField(default=False, verbose_name='فتح في نافذة جديدة')),
                ('css_class', models.CharField(blank=True, default='', max_length=200, verbose_name='كلاس CSS')),
                ('badge', models.CharField(blank=True, default='', max_length=50, verbose_name='شارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.menuitem', verbose_name='العنصر الأب')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='pages.page', verbose_name='الصفحة المرتبطة')),
            ],
            options={
                'verbose_name': 'عنصر قائمة',
                'verbose_name_plural': 'عناصر القوائم',
                'ordering': ['menu', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('hero', 'بطل الصفحة'), ('stats', 'إحصائيات'), ('features', 'الميزات'), ('how_it_works', 'كيف يعمل'), ('demo', 'عرض توضيحي'), ('testimonials', 'شهادات'), ('pricing', 'التسعير'), ('faq', 'أسئلة شائعة'), ('cta', 'دعوة للعمل'), ('text', 'نص'), ('image', 'صورة'), ('فيديو', 'Video'), ('gallery', 'معرض صور'), ('contact', 'تواصل معنا'), ('form', 'نموذج'), ('spacer', 'مسافة'), ('divider', 'فاصل'), ('services', 'خدمات'), ('portfolio', 'معرض أعمال'), ('team', 'الفريق'), ('partners', 'الشركاء'), ('custom_html', 'HTML مخصص')], max_length=20, verbose_name='نوع البلوك')),
                ('title_en', models.CharField(blank=True, default='', max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('title_ar', models.CharField(blank=True, default='', max_length=200, verbose_name='العنوان (عربي)')),
                ('subtitle_en', models.CharField(blank=True, default='', max_length=500, verbose_name='العنوان الفرعي (إنجليزي)')),
                ('subtitle_ar', models.CharField(blank=True, default='', max_length=500, verbose_name='العنوان الفرعي (عربي)')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='المحتوى')),
                ('styles', models.JSONField(blank=True, default=dict, verbose_name='الأنماط')),
                ('layout', models.JSONField(blank=True, default=dict, verbose_name='التخطيط')),
                ('animation', models.JSONField(blank=True, default=dict, verbose_name='الأنيميشن')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pages.page', verbose_name='الصفحة')),
            ],
            options={
                'verbose_name': 'بلوك',
                'verbose_name_plural': 'البلوكات',
                'ordering': ['page', 'order'],
            },
        ),
    ]
