# Generated by Django 5.2.16 on 2026-07-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'بطل الصفحة'), ('platform_hero', 'بطل الصفحة (المنصة)'), ('stats', 'إحصائيات'), ('platform_stats', 'إحصائيات (المنصة)'), ('features', 'الميزات'), ('how_it_works', 'كيف يعمل'), ('platform_how_it_works', 'كيف تعمل (المنصة)'), ('services_showcase', 'عرض الخدمات'), ('demo', 'عرض توضيحي'), ('testimonials', 'شهادات'), ('pricing', 'التسعير'), ('faq', 'أسئلة شائعة'), ('cta', 'دعوة للعمل'), ('text', 'نص'), ('image', 'صورة'), ('video', 'فيديو'), ('gallery', 'معرض صور'), ('contact', 'تواصل معنا'), ('form', 'نموذج'), ('spacer', 'مسافة'), ('divider', 'فاصل'), ('services', 'خدمات'), ('portfolio', 'معرض أعمال'), ('team', 'الفريق'), ('partners', 'الشركاء'), ('grade_showcase', 'عرض الصفوف'), ('subjects_grid', 'شبكة المواد'), ('custom_html', 'HTML مخصص')], max_length=30, verbose_name='نوع البلوك'),
        ),
    ]
