# Generated by Django 5.2.16 on 2026-07-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_add_new_block_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'بطل الصفحة'), ('platform_hero', 'بطل الصفحة (المنصة)'), ('stats', 'إحصائيات'), ('platform_stats', 'إحصائيات (المنصة)'), ('features', 'الميزات'), ('how_it_works', 'كيف يعمل'), ('platform_how_it_works', 'كيف تعمل (المنصة)'), ('services_showcase', 'عرض الخدمات'), ('demo', 'عرض توضيحي'), ('testimonials', 'شهادات'), ('pricing', 'التسعير'), ('faq', 'أسئلة شائعة'), ('cta', 'دعوة للعمل'), ('text', 'نص'), ('image', 'صورة'), ('video', 'فيديو'), ('gallery', 'معرض صور'), ('contact', 'تواصل معنا'), ('form', 'نموذج'), ('spacer', 'مسافة'), ('divider', 'فاصل'), ('services', 'خدمات'), ('portfolio', 'معرض أعمال'), ('team', 'الفريق'), ('partners', 'الشركاء'), ('grade_showcase', 'عرض الصفوف'), ('subjects_grid', 'شبكة المواد'), ('accordion', 'أقسام قابلة للطي'), ('tabs', 'تبويبات'), ('timeline', 'خط زمني'), ('countdown', 'عداد تنازلي'), ('newsletter', 'اشتراك بريد'), ('map', 'خريطة'), ('table', 'جدول بيانات'), ('icon_list', 'قائمة أيقونات'), ('logo_carousel', 'كاروسيل شعارات'), ('download', 'تحميل ملف'), ('code', 'بلوك كود'), ('custom_html', 'HTML مخصص'), ('blog_list', 'قائمة المدونة')], max_length=30, verbose_name='نوع البلوك'),
        ),
    ]
