# Generated by Django 5.2.16 on 2026-07-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_pageblock_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='translations',
            field=models.JSONField(blank=True, default=dict, verbose_name='الترجمات'),
        ),
        migrations.AddField(
            model_name='page',
            name='translations',
            field=models.JSONField(blank=True, default=dict, verbose_name='الترجمات'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='translations',
            field=models.JSONField(blank=True, default=dict, verbose_name='الترجمات'),
        ),
        migrations.AddField(
            model_name='pagetemplate',
            name='translations',
            field=models.JSONField(blank=True, default=dict, verbose_name='الترجمات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_translations',
            field=models.JSONField(blank=True, default=dict, verbose_name='ترجمات التذييل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='translations',
            field=models.JSONField(blank=True, default=dict, verbose_name='الترجمات'),
        ),
    ]
