# Generated by Django 5.2.16 on 2026-07-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_fix_content_restructure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagetemplate',
            options={'ordering': ['category', 'slug'], 'verbose_name': 'قالب صفحة', 'verbose_name_plural': 'قوالب الصفحات'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='page',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_description_ar',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_description_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_title_ar',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_title_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='subtitle_ar',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='pagetemplate',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='pagetemplate',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='pagetemplate',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='pagetemplate',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_text_ar',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_text_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_name_ar',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_name_en',
        ),
    ]
