# Generated by Django 5.2.16 on 2026-07-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_old_en_ar_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='الهاتف')),
                ('subject', models.CharField(blank=True, default='', max_length=300, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('service_interest', models.CharField(blank=True, default='', max_length=100, verbose_name='الخدمة المهتم بها')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('read', 'مقروءة'), ('replied', 'تم الرد'), ('archived', 'مؤرشفة')], default='new', max_length=20, verbose_name='الحالة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='متصفح المستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
    ]
