# Generated by Django 5.2.16 on 2026-07-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_add_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='الاسم')),
                ('locale', models.CharField(default='ar', max_length=10, verbose_name='اللغة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('unsubscribed', 'ملغي')], default='active', max_length=20, verbose_name='الحالة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مشترك في النشرة',
                'verbose_name_plural': 'مشتركو النشرة',
                'ordering': ['-created_at'],
            },
        ),
    ]
