# Generated by Django 5.2.16 on 2026-07-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_add_newsletter_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='العنوان'),
        ),
    ]
