# Generated by Django 5.2.16 on 2026-08-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_pageblock_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='required_role',
            field=models.CharField(choices=[('all', 'الجميع'), ('user', 'مستخدم عام'), ('instructor', 'مدرب'), ('admin', 'مدير'), ('support', 'دعم'), ('finance', 'مالية'), ('developer', 'مطور')], default='all', max_length=20, verbose_name='الدور المطلوب'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='service_context',
            field=models.CharField(choices=[('all', 'الكل'), ('academy', 'الأكاديمية'), ('school', 'آفاق مدرستي'), ('curriculum', 'المناهج'), ('lesson-plans', 'خطط الدروس'), ('ebooks', 'الكتب الإلكترونية'), ('dashboard', 'ساحة العمل'), ('profile', 'الملف الشخصي'), ('gamification', 'التلعيب'), ('subscriptions', 'الاشتراكات'), ('admin', 'لوحة الإدارة')], default='all', max_length=30, verbose_name='سياق الخدمة'),
        ),
    ]
