# Generated by Django 5.2.16 on 2026-08-09 06:19

import django.contrib.postgres.fields
from django.db import migrations, models


ALL_CONTEXTS = ['academy', 'school', 'curriculum', 'lesson-plans', 'ebooks',
                'dashboard', 'profile', 'gamification', 'subscriptions', 'admin']
ALL_ROLES = ['user', 'instructor', 'admin', 'support', 'finance', 'developer']


def to_array_literal(values):
    return '{' + ','.join(values) + '}'


def wrap_scalars(apps, schema_editor):
    """تحويل القيم المفردة إلى حرفي مصفوفة (Postgres literal) قبل تغيير نوع العمود."""
    MenuItem = apps.get_model('pages', 'MenuItem')
    for item in MenuItem.objects.all():
        ctx = item.service_context
        if isinstance(ctx, list):
            ctx = [c for c in ctx if c != 'all']
            item.service_context = to_array_literal(ctx or ALL_CONTEXTS) if ctx else '{}'
        elif ctx == 'all':
            item.service_context = to_array_literal(ALL_CONTEXTS)
        elif ctx:
            item.service_context = to_array_literal([ctx])
        else:
            item.service_context = '{}'

        role = item.required_role
        if isinstance(role, list):
            role = [r for r in role if r != 'all']
            item.required_role = to_array_literal(role or ALL_ROLES) if role else '{}'
        elif role == 'all':
            item.required_role = to_array_literal(ALL_ROLES)
        elif role:
            item.required_role = to_array_literal([role])
        else:
            item.required_role = '{}'
        item.save()


def unwrap_arrays(apps, schema_editor):
    """إرجاع المصفوفات إلى قيم مفردة (للرجوع للخلف)."""
    MenuItem = apps.get_model('pages', 'MenuItem')
    for item in MenuItem.objects.all():
        ctx = item.service_context or []
        item.service_context = 'all' if len(ctx) == len(ALL_CONTEXTS) else (ctx[0] if ctx else '')
        role = item.required_role or []
        item.required_role = 'all' if len(role) == len(ALL_ROLES) else (role[0] if role else '')
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_menuitem_required_role_menuitem_service_context'),
    ]

    operations = [
        # 1) توسيع الأعمدة مؤقتاً لاستيعاب حرفي المصفوفة
        migrations.AlterField(
            model_name='menuitem',
            name='required_role',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='service_context',
            field=models.TextField(blank=True, default=''),
        ),
        # 2) تحويل القيم المفردة إلى حرفي مصفوفة
        migrations.RunPython(wrap_scalars, reverse_code=unwrap_arrays),
        # 3) تحويل الأعمدة إلى مصفوفات
        migrations.AlterField(
            model_name='menuitem',
            name='required_role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('user', 'مستخدم عام'), ('instructor', 'مدرب'), ('admin', 'مدير'), ('support', 'دعم'), ('finance', 'مالية'), ('developer', 'مطور')], max_length=20, verbose_name='الدور'), blank=True, default=list, help_text='القائمة الفارغة = للجميع', size=None, verbose_name='الأدوار المطلوبة'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='service_context',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('academy', 'الأكاديمية'), ('school', 'آفاق مدرستي'), ('curriculum', 'المناهج'), ('lesson-plans', 'خطط الدروس'), ('ebooks', 'الكتب الإلكترونية'), ('dashboard', 'ساحة العمل'), ('profile', 'الملف الشخصي'), ('gamification', 'التلعيب'), ('subscriptions', 'الاشتراكات'), ('admin', 'لوحة الإدارة')], max_length=30, verbose_name='السياق'), blank=True, default=list, help_text='القائمة الفارغة = يظهر في كل الصفحات', size=None, verbose_name='سياقات الخدمة'),
        ),
    ]
