# Generated by Django 5.2.17 on 2026-08-16 17:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_seed_school_admin_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='required_role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('user', 'مستخدم عام'), ('instructor', 'مدرب'), ('admin', 'مدير'), ('support', 'دعم'), ('finance', 'مالية'), ('developer', 'مطور'), ('school_admin', 'مدير مدرسة'), ('teacher', 'معلم'), ('parent', 'ولي أمر'), ('student', 'طالب'), ('school_accountant', 'محاسب مدرسي'), ('school_transport_officer', 'مسؤول نقل'), ('school_librarian', 'أمين مكتبة')], max_length=40, verbose_name='الدور'), blank=True, default=list, help_text='القائمة الفارغة = للجميع', size=None, verbose_name='الأدوار المطلوبة'),
        ),
    ]
