# Generated by Django 5.2.16 on 2026-07-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('lesson_plan', 'خطة درس'), ('quiz', 'اختبار'), ('exploration', 'شرح'), ('chat', 'محادثة')], max_length=20, verbose_name='الميزة')),
                ('prompt', models.TextField(verbose_name='الاستعلام')),
                ('response', models.TextField(blank=True, verbose_name='الاستجابة')),
                ('model_used', models.CharField(max_length=100, verbose_name='النموذج')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='الرموز المستخدمة')),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='التكلفة')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='المدة بالمللي ثانية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تشغيل AI',
                'verbose_name_plural': 'تشغيلات AI',
                'ordering': ['-created_at'],
            },
        ),
    ]
