# Generated by Django 5.2.16 on 2026-07-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google Gemini')], default='google', max_length=50, verbose_name='المزود')),
                ('model_id', models.CharField(help_text='e.g. gemini-3.6-flash', max_length=100, verbose_name='معرف النموذج')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم (إنجليزي)')),
                ('description_ar', models.TextField(blank=True, default='', verbose_name='الوصف (عربي)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='الوصف (إنجليزي)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('max_tokens', models.IntegerField(default=4096, verbose_name='الحد الأقصى للرموز')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'نموذج AI',
                'verbose_name_plural': 'نماذج AI',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
    ]
