# Generated by Django 5.2.16 on 2026-07-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aimodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('provider_type', models.CharField(choices=[('google', 'Google Gemini')], default='google', max_length=50, verbose_name='نوع المزود')),
                ('encrypted_api_key', models.TextField(blank=True, default='', verbose_name='مفتاح API مشفر')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مزود AI',
                'verbose_name_plural': 'مزودو AI',
                'ordering': ['name'],
            },
        ),
    ]
