# Generated by Django 5.2.16 on 2026-07-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_aiprovider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodel',
            options={'ordering': ['sort_order'], 'verbose_name': 'نموذج AI', 'verbose_name_plural': 'نماذج AI'},
        ),
        migrations.AddField(
            model_name='aimodel',
            name='description',
            field=models.JSONField(blank=True, default=dict, verbose_name='الوصف (متعدد اللغات)'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='name',
            field=models.JSONField(blank=True, default=dict, verbose_name='الاسم (متعدد اللغات)'),
        ),
    ]
