# Generated by Django 5.2.16 on 2026-07-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_seed_default_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='الاسم (عربي)'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='الاسم (إنجليزي)'),
        ),
    ]
