# Generated by Django 5.2.16 on 2026-07-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_make_old_name_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('google', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)')], default='google', max_length=50, verbose_name='المزود'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='provider_type',
            field=models.CharField(choices=[('google', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)')], default='google', max_length=50, verbose_name='نوع المزود'),
        ),
    ]
