# Generated by Django 5.2.16 on 2026-07-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_add_openai_anthropic_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovider',
            name='base_url',
            field=models.CharField(blank=True, default='', help_text='For Ollama / OpenAI-compatible providers', max_length=500, verbose_name='رابط API'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('google', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('ollama', 'Ollama'), ('openai_compatible', 'OpenAI Compatible')], default='google', max_length=50, verbose_name='المزود'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='provider_type',
            field=models.CharField(choices=[('google', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('ollama', 'Ollama'), ('openai_compatible', 'OpenAI Compatible')], default='google', max_length=50, verbose_name='نوع المزود'),
        ),
    ]
