# Generated by Django 5.2.16 on 2026-07-29 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_old_en_ar_fields'),
        ('ai', '0013_migrate_providertype_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القالب')),
                ('feature_key', models.CharField(db_index=True, default='lesson_plan', max_length=50, verbose_name='مفتاح الخدمة')),
                ('language', models.CharField(db_index=True, default='ar', max_length=10, verbose_name='اللغة')),
                ('learner_stage', models.CharField(blank=True, choices=[('early_primary', 'الصف الأول الأساسي المبكر'), ('primary', 'المرحلة الأساسية'), ('middle', 'المرحلة المتوسطة'), ('secondary', 'المرحلة الثانوية'), ('university', 'الجامعية'), ('professional', 'مهني')], default='', max_length=32, verbose_name='المرحلة التعليمية')),
                ('template_body', models.TextField(verbose_name='نص البرومبت (Template)')),
                ('priority', models.IntegerField(default=0, help_text='كلما زاد الرقم كانت الأولوية أعلى عند تساوي التخصص', verbose_name='الأولوية')),
                ('is_default', models.BooleanField(default=False, verbose_name='قالب افتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('version', models.IntegerField(default=1, verbose_name='الإصدار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.curriculum', verbose_name='المنهاج')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'قالب برومبت الذكاء الاصطناعي',
                'verbose_name_plural': 'قوالب برومبت الذكاء الاصطناعي',
                'ordering': ['-priority', '-updated_at'],
            },
        ),
    ]
