# Generated by Django 5.2.16 on 2026-07-30 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_curriculumdocument'),
        ('ai', '0015_seed_prompt_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePromptProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_stage', models.CharField(blank=True, choices=[('early_primary', 'Early Primary'), ('primary', 'Primary'), ('middle', 'Middle'), ('secondary', 'Secondary'), ('university', 'University'), ('professional', 'Professional')], default='', max_length=32, verbose_name='Education Stage')),
                ('language_guidance', models.TextField(blank=True, help_text='Guidance on language level suitable for this grade', verbose_name='Language Guidance')),
                ('content_depth_guidance', models.TextField(blank=True, verbose_name='Content Depth Guidance')),
                ('activity_guidance', models.TextField(blank=True, verbose_name='Activity Guidance')),
                ('materials_guidance', models.TextField(blank=True, verbose_name='Materials Guidance')),
                ('assessment_guidance', models.TextField(blank=True, verbose_name='Assessment Guidance')),
                ('forbidden_terms', models.JSONField(blank=True, default=list, verbose_name='Forbidden Terms')),
                ('discouraged_patterns', models.JSONField(blank=True, default=list, verbose_name='Discouraged Patterns')),
                ('extra_instructions', models.JSONField(blank=True, default=list, verbose_name='Extra Instructions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade Prompt Profile',
                'verbose_name_plural': 'Grade Prompt Profiles',
            },
        ),
        migrations.CreateModel(
            name='SubjectPromptProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_guidance', models.TextField(blank=True, verbose_name='Language Guidance')),
                ('content_depth_guidance', models.TextField(blank=True, verbose_name='Content Depth Guidance')),
                ('activity_guidance', models.TextField(blank=True, verbose_name='Activity Guidance')),
                ('materials_guidance', models.TextField(blank=True, verbose_name='Materials Guidance')),
                ('assessment_guidance', models.TextField(blank=True, verbose_name='Assessment Guidance')),
                ('forbidden_terms', models.JSONField(blank=True, default=list, verbose_name='Forbidden Terms')),
                ('discouraged_patterns', models.JSONField(blank=True, default=list, verbose_name='Discouraged Patterns')),
                ('extra_instructions', models.JSONField(blank=True, default=list, verbose_name='Extra Instructions')),
                ('topic_rules', models.TextField(blank=True, help_text='Subject-specific topic constraints', verbose_name='Topic Rules')),
                ('override_language_guidance', models.BooleanField(default=False, verbose_name='Override Language Guidance')),
                ('override_content_depth_guidance', models.BooleanField(default=False, verbose_name='Override Content Depth')),
                ('override_activity_guidance', models.BooleanField(default=False, verbose_name='Override Activity Guidance')),
                ('override_materials_guidance', models.BooleanField(default=False, verbose_name='Override Materials Guidance')),
                ('override_assessment_guidance', models.BooleanField(default=False, verbose_name='Override Assessment Guidance')),
                ('merge_forbidden_terms', models.BooleanField(default=True, verbose_name='Merge Forbidden Terms')),
                ('merge_discouraged_patterns', models.BooleanField(default=True, verbose_name='Merge Discouraged Patterns')),
                ('merge_extra_instructions', models.BooleanField(default=True, verbose_name='Merge Extra Instructions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject Prompt Profile',
                'verbose_name_plural': 'Subject Prompt Profiles',
            },
        ),
        migrations.AlterModelOptions(
            name='aimodel',
            options={'ordering': ['sort_order'], 'verbose_name': 'AI Model', 'verbose_name_plural': 'AI Models'},
        ),
        migrations.AlterModelOptions(
            name='aiprovider',
            options={'ordering': ['name'], 'verbose_name': 'AI Provider', 'verbose_name_plural': 'AI Providers'},
        ),
        migrations.AlterModelOptions(
            name='airun',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Run', 'verbose_name_plural': 'AI Runs'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='prompttemplate',
            options={'ordering': ['-priority', '-updated_at'], 'verbose_name': 'AI Prompt Template', 'verbose_name_plural': 'AI Prompt Templates'},
        ),
        migrations.AlterModelOptions(
            name='providertype',
            options={'ordering': ['sort_order', 'name_ar'], 'verbose_name': 'Provider Type', 'verbose_name_plural': 'Provider Types'},
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='description',
            field=models.JSONField(blank=True, default=dict, verbose_name='Description (Multilingual)'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='description_ar',
            field=models.TextField(blank=True, default='', verbose_name='Description (Arabic)'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='max_tokens',
            field=models.IntegerField(default=4096, verbose_name='Max Tokens'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_id',
            field=models.CharField(help_text='e.g. gemini-3.6-flash', max_length=100, verbose_name='Model ID'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='name',
            field=models.JSONField(blank=True, default=dict, verbose_name='Name (Multilingual)'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='base_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='API URL'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='encrypted_api_key',
            field=models.TextField(blank=True, default='', verbose_name='Encrypted API Key'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='provider_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='ai.providertype', verbose_name='Provider Type'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='airun',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='airun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='airun',
            name='duration_ms',
            field=models.IntegerField(default=0, verbose_name='Duration (ms)'),
        ),
        migrations.AlterField(
            model_name='airun',
            name='feature',
            field=models.CharField(choices=[('lesson_plan', 'Lesson Plan'), ('quiz', 'Quiz'), ('exploration', 'Explanation'), ('chat', 'Chat')], max_length=20, verbose_name='Feature'),
        ),
        migrations.AlterField(
            model_name='airun',
            name='model_used',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='airun',
            name='prompt',
            field=models.TextField(verbose_name='Prompt'),
        ),
        migrations.AlterField(
            model_name='airun',
            name='response',
            field=models.TextField(blank=True, verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='airun',
            name='tokens_used',
            field=models.IntegerField(default=0, verbose_name='Tokens Used'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tokens',
            field=models.IntegerField(default=0, verbose_name='Tokens'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.curriculum', verbose_name='Curriculum'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='feature_key',
            field=models.CharField(db_index=True, default='lesson_plan', max_length=50, verbose_name='Feature Key'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default Template'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='language',
            field=models.CharField(db_index=True, default='ar', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='learner_stage',
            field=models.CharField(blank=True, choices=[('early_primary', 'Early Primary'), ('primary', 'Primary'), ('middle', 'Middle'), ('secondary', 'Secondary'), ('university', 'University'), ('professional', 'Professional')], default='', max_length=32, verbose_name='Education Stage'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Template Name'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher number = higher priority when specialization matches', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='template_body',
            field=models.TextField(verbose_name='Template Body'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='version',
            field=models.IntegerField(default=1, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='providertype',
            name='code',
            field=models.CharField(help_text='e.g. google, openai, ollama', max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='providertype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='providertype',
            name='default_base_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Default URL'),
        ),
        migrations.AlterField(
            model_name='providertype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='providertype',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='providertype',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='providertype',
            name='needs_api_key',
            field=models.BooleanField(default=True, verbose_name='Needs API Key'),
        ),
        migrations.AlterField(
            model_name='providertype',
            name='needs_base_url',
            field=models.BooleanField(default=False, verbose_name='Needs API URL'),
        ),
        migrations.AlterField(
            model_name='providertype',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='providertype',
            name='supports_fetching',
            field=models.BooleanField(default=True, verbose_name='Supports Model Fetching'),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(fields=('feature_key', 'language', 'version'), name='unique_prompt_version'),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('feature_key', 'language'), name='unique_active_default_prompt_per_feature_lang'),
        ),
        migrations.AddField(
            model_name='gradepromptprofile',
            name='grade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_profile', to='academics.grade', verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='subjectpromptprofile',
            name='grade_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_profiles', to='ai.gradepromptprofile', verbose_name='Grade Profile'),
        ),
        migrations.AddField(
            model_name='subjectpromptprofile',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_profiles', to='academics.subject', verbose_name='Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectpromptprofile',
            unique_together={('grade_profile', 'subject')},
        ),
    ]
