# Generated by Django 5.2.16 on 2026-07-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0016_prompt_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='user_message_template',
            field=models.TextField(blank=True, default='', help_text='Short user message sent alongside the system prompt. Can use Django template variables.', verbose_name='User Message Template'),
        ),
    ]
