# Generated by Django 5.2.16 on 2026-08-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0023_update_refine_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPromptProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='e.g. الأردن، السعودية', max_length=100, unique=True, verbose_name='Country')),
                ('educational_framework', models.TextField(blank=True, help_text='Ministry guidelines and pedagogical rules for this country', verbose_name='Educational Framework & Guidelines')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country Prompt Profile',
                'verbose_name_plural': 'Country Prompt Profiles',
            },
        ),
    ]
