# Generated by Django 5.2.16 on 2026-08-03 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Code')),
                ('name', models.JSONField(default=dict, verbose_name='Name (Multilingual)')),
                ('description', models.JSONField(default=dict, verbose_name='Description (Multilingual)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='Currency')),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='Billing Period')),
                ('duration_days', models.IntegerField(default=30, verbose_name='Duration (days)')),
                ('level', models.IntegerField(default=0, help_text='0=free, 1=basic, 2=pro/school, 3=enterprise', verbose_name='Access Level')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Features (Multilingual)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_provider', models.CharField(blank=True, default='', max_length=32, verbose_name='Payment Provider')),
                ('payment_session_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Payment Session ID')),
                ('payment_transaction_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Payment Transaction ID')),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price Paid')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='Currency')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Ends At')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
