# Generated by Django 5.2.16 on 2026-08-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='prices',
            field=models.JSONField(blank=True, default=dict, help_text='Per-currency display prices, e.g. {"SAR": "9.99", "JOD": "1.90", "USD": "2.66"}. The gateway always charges in the account currency.', verbose_name='Prices per Currency'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='display_currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Display Currency'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='display_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Display Price'),
        ),
    ]
