# Generated by Django 5.2.16 on 2026-08-03 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_seed_plan_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Code')),
                ('name', models.JSONField(default=dict, verbose_name='Name (Multilingual)')),
                ('description', models.JSONField(blank=True, default=dict, verbose_name='Description (Multilingual)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan Service',
                'verbose_name_plural': 'Plan Services',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanServiceLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.PositiveIntegerField(blank=True, help_text='Number of uses allowed per period. Leave empty for unlimited.', null=True, verbose_name='Usage Limit')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=20, verbose_name='Period')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_limits', to='subscriptions.plan')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_limits', to='subscriptions.planservice')),
            ],
            options={
                'verbose_name': 'Plan Service Limit',
                'verbose_name_plural': 'Plan Service Limits',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('plan', 'service')},
            },
        ),
        migrations.CreateModel(
            name='ServiceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(max_length=16, verbose_name='Period Key')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Used Count')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='subscriptions.planservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Usage',
                'verbose_name_plural': 'Service Usages',
                'unique_together': {('user', 'service', 'period_key')},
            },
        ),
    ]
