# Generated by Django 5.2.16 on 2026-08-03 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_plan_seats(apps, schema_editor):
    Plan = apps.get_model('subscriptions', 'Plan')
    defaults = {
        'school': {'seats': 25, 'extra_seat_price': '5.00'},
        'enterprise': {'seats': 100, 'extra_seat_price': '10.00'},
    }
    for code, data in defaults.items():
        Plan.objects.filter(code=code).update(**data)


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_seed_services_and_free_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('teacher', 'Teacher')], default='teacher', max_length=20, verbose_name='Role')),
                ('status', models.CharField(choices=[('pending', 'Invited'), ('active', 'Active'), ('removed', 'Removed')], default='pending', max_length=20, verbose_name='Status')),
                ('invite_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Invite Email')),
                ('invite_token', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Invite Token')),
                ('invited_at', models.DateTimeField(blank=True, null=True, verbose_name='Invited At')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Joined At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Membership',
                'verbose_name_plural': 'Organization Memberships',
                'ordering': ['-status', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Seats Count')),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price Paid')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='Currency')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_provider', models.CharField(blank=True, default='', max_length=32, verbose_name='Payment Provider')),
                ('payment_session_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Payment Session ID')),
                ('payment_transaction_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Payment Transaction ID')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seat Purchase',
                'verbose_name_plural': 'Seat Purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='extra_seat_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per additional teacher seat beyond the included seats (0 disables extra seats).', max_digits=10, verbose_name='Extra Seat Price'),
        ),
        migrations.AddField(
            model_name='plan',
            name='seats',
            field=models.PositiveIntegerField(default=0, help_text='Number of teacher seats included in the base price (school/enterprise plans).', verbose_name='Teacher Seats'),
        ),
        migrations.AlterField(
            model_name='serviceusage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('extra_seats', models.PositiveIntegerField(default=0, verbose_name='Extra Seats')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='subscriptions.plan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='serviceusage',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Set when the usage is charged to an organization (shared pool) instead of a single user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_usages', to='subscriptions.organization'),
        ),
        migrations.AddConstraint(
            model_name='serviceusage',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'service', 'period_key'), name='uniq_org_service_period'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='subscriptions.organization'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seatpurchase',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_purchases', to='subscriptions.organization'),
        ),
        migrations.AddField(
            model_name='seatpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(seed_plan_seats, migrations.RunPython.noop),
    ]
