# Generated by Django 5.2.16 on 2026-08-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_organizationmembership_seatpurchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='JOD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='seatpurchase',
            name='currency',
            field=models.CharField(default='JOD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='JOD', max_length=3, verbose_name='Currency'),
        ),
    ]
