# Generated by Django 5.2.16 on 2026-08-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_plan_currency_alter_seatpurchase_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Code')),
                ('name', models.JSONField(default=dict, verbose_name='Name (Multilingual)')),
                ('symbol', models.CharField(blank=True, default='', max_length=8, verbose_name='Symbol')),
                ('rate', models.DecimalField(decimal_places=6, default=1, help_text='How many units of this currency equal 1 unit of the base currency (JOD).', max_digits=12, verbose_name='Rate to Base')),
                ('is_base', models.BooleanField(default=False, verbose_name='Base Currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
