# Generated by Django 5.2.16 on 2026-07-28 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EbookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('translations', models.JSONField(blank=True, default=dict, verbose_name='الترجمات')),
                ('icon', models.CharField(default='📚', max_length=10, verbose_name='الأيقونة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تصنيف كتاب',
                'verbose_name_plural': 'تصنيفات الكتب',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('translations', models.JSONField(blank=True, default=dict, verbose_name='الترجمات')),
                ('cover_image', models.URLField(blank=True, default='', verbose_name='صورة الغلاف')),
                ('file_url', models.URLField(blank=True, default='', verbose_name='رابط الملف')),
                ('preview_url', models.URLField(blank=True, default='', verbose_name='رابط المعاينة')),
                ('author_translations', models.JSONField(blank=True, default=dict, verbose_name='ترجمات المؤلف')),
                ('author_avatar', models.URLField(blank=True, default='', verbose_name='صورة المؤلف')),
                ('pages_count', models.IntegerField(default=0, verbose_name='عدد الصفحات')),
                ('file_size', models.CharField(blank=True, default='', max_length=50, verbose_name='حجم الملف')),
                ('file_format', models.CharField(default='PDF', max_length=20, verbose_name='صيغة الملف')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('download_count', models.IntegerField(default=0, verbose_name='عدد التحميلات')),
                ('related_service', models.CharField(blank=True, default='', max_length=200, verbose_name='رابط الخدمة المرتبطة')),
                ('tags', models.CharField(blank=True, default='', max_length=500, verbose_name='الوسوم')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebooks', to='ebooks.ebookcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'كتاب إلكتروني',
                'verbose_name_plural': 'الكتب الإلكترونية',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
