# Generated by Django 5.2.16 on 2026-07-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='access_level',
            field=models.CharField(choices=[('free', 'مجاني'), ('basic', 'أساسي'), ('pro', 'برو'), ('enterprise', 'مؤسسي')], default='free', max_length=20, verbose_name='مستوى الوصول'),
        ),
    ]
