# Generated by Django 5.2.16 on 2026-08-09 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0002_ebook_access_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebooks', to=settings.AUTH_USER_MODEL, verbose_name='المؤلف'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='مجاني'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=1, default=10, help_text='نسبة رسوم المنصة من سعر الشراء، والباقي للمؤلف', max_digits=4, verbose_name='رسوم المنصة %'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='السعر'),
        ),
        migrations.CreateModel(
            name='EbookPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع'), ('refunded', 'مسترد')], default='pending', max_length=20, verbose_name='الحالة')),
                ('payment_provider', models.CharField(blank=True, default='', max_length=32, verbose_name='مزوّد الدفع')),
                ('payment_session_id', models.CharField(blank=True, default='', max_length=255, verbose_name='معرّف الجلسة')),
                ('payment_transaction_id', models.CharField(blank=True, default='', max_length=255, verbose_name='معرّف العملية')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('currency', models.CharField(default='JOD', max_length=3, verbose_name='العملة')),
                ('display_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر المعروض')),
                ('display_currency', models.CharField(default='JOD', max_length=3, verbose_name='عملة العرض')),
                ('purchased_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الشراء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='ebooks.ebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebook_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'شراء كتاب',
                'verbose_name_plural': 'مشتريات الكتب',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'ebook')},
            },
        ),
    ]
