# Generated by Django 5.2.16 on 2026-08-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0004_add_userrole_fk_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='author',
        ),
    ]
