# Generated by Django 5.2.16 on 2026-07-24 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('level', models.IntegerField(verbose_name='المستوى')),
            ],
            options={
                'verbose_name': 'صف',
                'verbose_name_plural': 'الصفوف',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('country', models.CharField(max_length=100, verbose_name='الدولة')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='academics.grade')),
            ],
            options={
                'verbose_name': 'منهج',
                'verbose_name_plural': 'المناهج',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academics.curriculum')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
                'ordering': ['order'],
            },
        ),
    ]
