# Generated by Django 5.2.16 on 2026-07-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_populate_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='name_en',
        ),
    ]
