# Generated by Django 5.2.16 on 2026-07-29 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_old_en_ar_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المستند/الملف')),
                ('file', models.FileField(upload_to='curricula/documents/', verbose_name='ملف المنهج (PDF/TXT)')),
                ('extracted_text', models.TextField(blank=True, verbose_name='النص المستخرج / محتوى المنهج')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='academics.curriculum', verbose_name='المنهج الدراسي')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='academics.subject', verbose_name='المادة الدراسية')),
            ],
            options={
                'verbose_name': 'مستند منهج ومادة',
                'verbose_name_plural': 'مستندات المناهج والمواد (Curriculum Documents)',
            },
        ),
    ]
