# Generated by Django 5.2.16 on 2026-08-02 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_curriculumdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='content',
            field=models.TextField(blank=True, help_text='مقتطفات من محتوى المنهاج الرسمي لحقنها في توليد الخطط', verbose_name='محتوى الوحدة الرسمي'),
        ),
        migrations.AddField(
            model_name='unit',
            name='outcomes',
            field=models.JSONField(blank=True, default=list, help_text='قائمة نواتج التعلم الرسمية لهذه الوحدة', verbose_name='نواتج التعلم'),
        ),
        migrations.AddField(
            model_name='unit',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='academics.subject', verbose_name='المادة الدراسية'),
        ),
    ]
