# Generated by Django 5.2.16 on 2026-08-04 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_unit_content_unit_outcomes_unit_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['id'], 'verbose_name': 'مادة', 'verbose_name_plural': 'المواد'},
        ),
    ]
