# Generated by Django 5.2.16 on 2026-08-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_subject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumdocument',
            name='external_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='رابط الملف الخارجي (الموقع الرسمي)'),
        ),
        migrations.AlterField(
            model_name='curriculumdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='curricula/documents/', verbose_name='ملف المنهج (PDF/TXT)'),
        ),
    ]
