# Generated by Django 5.2.16 on 2026-08-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_curriculumdocument_external_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='country',
            field=models.CharField(db_index=True, max_length=100, verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='year',
            field=models.IntegerField(db_index=True, verbose_name='السنة'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='الترتيب'),
        ),
        migrations.AddIndex(
            model_name='curriculum',
            index=models.Index(fields=['country', 'year'], name='academics_c_country_8c116e_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['curriculum', 'subject'], name='academics_u_curricu_9563f3_idx'),
        ),
    ]
