# Generated by Django 5.2.16 on 2026-08-19 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_curriculum_country_alter_curriculum_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='has_tracks',
            field=models.BooleanField(default=False, help_text='عند التفعيل: يجب إنشاء تخصصات (AcademicTrack) لهذا الصف قبل إنشاء الأقسام', verbose_name='يدعم التخصصات/الشعب'),
        ),
        migrations.CreateModel(
            name='AcademicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', models.JSONField(blank=True, default=dict, verbose_name='الترجمات')),
                ('code', models.CharField(help_text='رمز فريد للحقل مثل scientific_engineering', max_length=50, verbose_name='الرمز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='academics.grade', verbose_name='الصف')),
            ],
            options={
                'verbose_name': 'تخصص أكاديمي',
                'verbose_name_plural': 'التخصصات الأكاديمية',
                'ordering': ['grade', 'order', 'id'],
                'unique_together': {('grade', 'code')},
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='track',
            field=models.ForeignKey(blank=True, help_text='فارغ = منهج عام لكل التخصصات، مملو = منهج خاص بالتخصص', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curricula', to='academics.academictrack', verbose_name='التخصص'),
        ),
    ]
