# Generated by Django 5.2.16 on 2026-08-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_grade_has_tracks_academictrack_curriculum_track'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academictrack',
            options={'ordering': ['country', 'year', 'grade', 'order', 'id'], 'verbose_name': 'تخصص أكاديمي', 'verbose_name_plural': 'التخصصات الأكاديمية'},
        ),
        migrations.AlterUniqueTogether(
            name='academictrack',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='academictrack',
            name='country',
            field=models.CharField(db_index=True, default='السعودية', max_length=100, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='academictrack',
            name='year',
            field=models.IntegerField(db_index=True, default=2026, verbose_name='السنة'),
        ),
        migrations.AlterUniqueTogether(
            name='academictrack',
            unique_together={('country', 'year', 'grade', 'code')},
        ),
        migrations.AddIndex(
            model_name='academictrack',
            index=models.Index(fields=['country', 'year'], name='academics_a_country_4d6516_idx'),
        ),
    ]
