# Generated by Django 5.2.16 on 2026-08-09 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_level',
            field=models.CharField(choices=[('free', 'مجاني'), ('basic', 'أساسي'), ('pro', 'برو'), ('enterprise', 'مؤسسي')], default='free', max_length=20, verbose_name='Access Level'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='المدرب'),
        ),
        migrations.AddField(
            model_name='course',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=1, default=10, help_text='نسبة رسوم المنصة من سعر الشراء، والباقي للمدرب', max_digits=4, verbose_name='Platform Fee %'),
        ),
        migrations.CreateModel(
            name='CoursePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع'), ('refunded', 'مسترد')], default='pending', max_length=20, verbose_name='الحالة')),
                ('payment_provider', models.CharField(blank=True, default='', max_length=32, verbose_name='مزوّد الدفع')),
                ('payment_session_id', models.CharField(blank=True, default='', max_length=255, verbose_name='معرّف الجلسة')),
                ('payment_transaction_id', models.CharField(blank=True, default='', max_length=255, verbose_name='معرّف العملية')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('currency', models.CharField(default='JOD', max_length=3, verbose_name='العملة')),
                ('display_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر المعروض')),
                ('display_currency', models.CharField(default='JOD', max_length=3, verbose_name='عملة العرض')),
                ('purchased_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الشراء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'شراء دورة',
                'verbose_name_plural': 'مشتريات الدورات',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
