# Generated by Django 5.2.16 on 2026-08-19 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_access_level_course_instructor_and_more'),
        ('users', '0017_add_userrole_and_roles_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructed_courses', to='users.userrole', verbose_name='Instructor Role'),
        ),
    ]
