# Generated by Django 5.2.16 on 2026-08-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['name'], 'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['rarity', 'name'], 'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.AlterModelOptions(
            name='badgecategory',
            options={'verbose_name': 'Badge Category', 'verbose_name_plural': 'Badge Categories'},
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-start_date'], 'verbose_name': 'Challenge', 'verbose_name_plural': 'Challenges'},
        ),
        migrations.AlterModelOptions(
            name='challengeparticipant',
            options={'verbose_name': 'Challenge Participant', 'verbose_name_plural': 'Challenge Participants'},
        ),
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'verbose_name': 'Leaderboard', 'verbose_name_plural': 'Leaderboards'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['number'], 'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
        migrations.AlterModelOptions(
            name='pointstransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Points Transaction', 'verbose_name_plural': 'Points Transactions'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'verbose_name': 'User Achievement', 'verbose_name_plural': 'User Achievements'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'verbose_name': 'User Badge', 'verbose_name_plural': 'User Badges'},
        ),
        migrations.AlterModelOptions(
            name='userstreak',
            options={'verbose_name': 'User Streak', 'verbose_name_plural': 'User Streaks'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('single', 'Single'), ('progress', 'Progress'), ('secret', 'Secret')], default='single', max_length=15),
        ),
        migrations.AlterField(
            model_name='badge',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=15),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='duration',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('special', 'Special')], max_length=15),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='category',
            field=models.CharField(choices=[('points', 'Points'), ('lessons', 'Lessons Created'), ('streak', 'Longest Streak'), ('badges', 'Badges')], max_length=15),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=15),
        ),
    ]
