from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


class LessonPlan(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'draft', _('Draft')
        PUBLISHED = 'published', _('Published')
        ARCHIVED = 'archived', _('Archived')

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='lesson_plans')
    title = models.CharField(_('Title'), max_length=255)
    subject = models.ForeignKey('academics.Subject', on_delete=models.SET_NULL, null=True, related_name='lesson_plans')
    grade = models.ForeignKey('academics.Grade', on_delete=models.SET_NULL, null=True, related_name='lesson_plans')
    plan_data = models.JSONField(_('Plan Data'))
    generated_by = models.CharField(_('Generated By'), max_length=10, default='ai')
    ai_model_used = models.CharField(_('AI Model Used'), max_length=100, blank=True)
    status = models.CharField(_('Status'), max_length=15, choices=Status.choices, default=Status.DRAFT)

    # Marketplace & Community
    is_public = models.BooleanField(_('Public (Marketplace)'), default=False)
    likes_count = models.IntegerField(_('Likes Count'), default=0)
    clones_count = models.IntegerField(_('Clones Count'), default=0)
    downloads_count = models.IntegerField(_('Downloads Count'), default=0)
    original_plan = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='clones', verbose_name=_('Original Plan'))

    created_at = models.DateTimeField(_('Created At'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated At'), auto_now=True)

    class Meta:
        verbose_name = _('Lesson Plan')
        verbose_name_plural = _('Lesson Plans')
        ordering = ['-created_at']

    def __str__(self):
        return self.title


class LessonPlanRefinement(models.Model):
    lesson_plan = models.ForeignKey(LessonPlan, on_delete=models.CASCADE, related_name='refinements', verbose_name=_('Lesson Plan'))
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_('User'))
    user_prompt = models.TextField(_('Refinement Prompt'))
    ai_response = models.TextField(_('AI Response'))
    created_at = models.DateTimeField(_('Created At'), auto_now_add=True)

    class Meta:
        verbose_name = _('Lesson Plan Refinement')
        verbose_name_plural = _('Lesson Plan Refinements')
        ordering = ['created_at']

    def __str__(self):
        return _('Refinement for %(plan)s') % {'plan': self.lesson_plan.title}
