export const BLOCK_TYPES: Record<string, { i18nKey: string; icon: string }> = {
  platform_hero: { i18nKey: "admin.blockPlatformHero", icon: "🏢" },
  platform_stats: { i18nKey: "admin.blockPlatformStats", icon: "📈" },
  platform_how_it_works: { i18nKey: "admin.blockPlatformHowItWorks", icon: "🔄" },
  services_showcase: { i18nKey: "admin.blockServicesShowcase", icon: "🔧" },
  hero: { i18nKey: "admin.blockHero", icon: "🎯" },
  stats: { i18nKey: "admin.blockStats", icon: "📊" },
  features: { i18nKey: "admin.blockFeatures", icon: "⭐" },
  how_it_works: { i18nKey: "admin.blockHowItWorks", icon: "🔄" },
  demo: { i18nKey: "admin.blockDemo", icon: "🖥️" },
  testimonials: { i18nKey: "admin.blockTestimonials", icon: "💬" },
  pricing: { i18nKey: "admin.blockPricing", icon: "💰" },
  faq: { i18nKey: "admin.blockFaq", icon: "❓" },
  cta: { i18nKey: "admin.blockCta", icon: "📢" },
  grade_showcase: { i18nKey: "admin.blockGradeShowcase", icon: "📚" },
  subjects_grid: { i18nKey: "admin.blockSubjectsGrid", icon: "📐" },
  partners: { i18nKey: "admin.blockPartners", icon: "🤝" },
  portfolio: { i18nKey: "admin.blockPortfolio", icon: "🖼️" },
  text: { i18nKey: "admin.blockText", icon: "📝" },
  image: { i18nKey: "admin.blockImage", icon: "🖼️" },
  video: { i18nKey: "admin.blockVideo", icon: "🎬" },
  gallery: { i18nKey: "admin.blockGallery", icon: "🖼️" },
  contact: { i18nKey: "admin.blockContact", icon: "📬" },
  form: { i18nKey: "admin.blockForm", icon: "📋" },
  spacer: { i18nKey: "admin.blockSpacer", icon: "↕️" },
  divider: { i18nKey: "admin.blockDivider", icon: "➖" },
  services: { i18nKey: "admin.blockServices", icon: "🔧" },
  team: { i18nKey: "admin.blockTeam", icon: "👥" },
  accordion: { i18nKey: "admin.blockAccordion", icon: "🔽" },
  tabs: { i18nKey: "admin.blockTabs", icon: "📑" },
  timeline: { i18nKey: "admin.blockTimeline", icon: "📅" },
  countdown: { i18nKey: "admin.blockCountdown", icon: "⏰" },
  newsletter: { i18nKey: "admin.blockNewsletter", icon: "✉️" },
  map: { i18nKey: "admin.blockMap", icon: "🗺️" },
  table: { i18nKey: "admin.blockTable", icon: "📊" },
  icon_list: { i18nKey: "admin.blockIconList", icon: "📋" },
  logo_carousel: { i18nKey: "admin.blockLogoCarousel", icon: "🏢" },
  download: { i18nKey: "admin.blockDownload", icon: "⬇️" },
  code: { i18nKey: "admin.blockCode", icon: "💻" },
  custom_html: { i18nKey: "admin.blockCustomHtml", icon: "💻" },
  blog_list: { i18nKey: "admin.blockBlogList", icon: "📝" },
  chat_greeting: { i18nKey: "admin.blockChatGreeting", icon: "🤖" },
};

export const TEMPLATE_ICONS: Record<string, string> = {
  landing: "🚀", default: "📄", about: "ℹ️", contact: "📬", custom: "🎨",
};
